const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={mode:'earth',selected:'Earth',rot:-8,tilt:8,drag:false,lastX:0,layerEvents:true};
const data={
 'Solar System':{sub:'Planetary system · Milky Way',trust:'Verified Reality',source:'Astronomical catalogues & mission data',facts:[['STAR','The Sun'],['PLANETS','8'],['AGE','≈ 4.57B years'],['GALAXY','Milky Way']],summary:'A connected astronomical system linking planets, moons, minor bodies, missions, observations and scientific models.'},
 Earth:{sub:'Terrestrial planet · Solar System',trust:'Verified Reality',source:'Scientific & geospatial source layer',facts:[['AGE','≈ 4.54B years'],['DIAMETER','12,742 km'],['SURFACE','510.1M km²'],['MOONS','1']],summary:'A living planetary knowledge node connecting terrain, atmosphere, oceans, life, cities, history and live events.'},
 Rome:{sub:'City · Lazio · Italy',trust:'Verified Reality',source:'Geospatial, cultural & historical layers',facts:[['COUNTRY','Italy'],['REGION','Lazio'],['FOUNDED','753 BCE · traditional'],['POPULATION','Metro scale']],summary:'Rome can be explored as a present-day city, an archaeological system and a sequence of historical reconstructions.'},
 Everest:{sub:'Mountain · Himalayas',trust:'Verified Reality',source:'Topographic & geographic layers',facts:[['ELEVATION','8,848.86 m'],['RANGE','Himalayas'],['BORDER','Nepal · China'],['TYPE','Mountain']],summary:'A geographical object connected to geology, climate, expeditions, human history and live weather layers.'},
 'Kīlauea':{sub:'Shield volcano · Hawaiʻi',trust:'Verified Reality',source:'Geological & hazard layers',facts:[['TYPE','Shield volcano'],['STATUS','Active'],['ISLAND','Hawaiʻi'],['LAYER','Live-ready']],summary:'A dynamic Earth object combining geology, eruptive history, monitoring data and hazard information.'},
 Moon:{sub:'Natural satellite · Earth system',trust:'Verified Reality',source:'Lunar mission & astronomical data',facts:[['DISTANCE','384,400 km avg'],['DIAMETER','3,474.8 km'],['GRAVITY','1.62 m/s²'],['ORBIT','27.3 days']],summary:'Explore the Moon as terrain, geology, mission history and a destination for immersive learning.'},
 Mars:{sub:'Terrestrial planet · Solar System',trust:'Verified Reality',source:'Planetary mission & orbital datasets',facts:[['DAY','24h 37m'],['MOONS','2'],['DIAMETER','6,779 km'],['ATMOSPHERE','CO₂ rich']],summary:'A planetary knowledge node linking orbital imagery, rover missions, geology, climate and scientific reconstructions.'},
 Jupiter:{sub:'Gas giant · Solar System',trust:'Verified Reality',source:'Astronomical catalogues & missions',facts:[['TYPE','Gas giant'],['MOONS','95+ known'],['DAY','≈ 9h 56m'],['FEATURE','Great Red Spot']],summary:'Explore a giant planetary system, its atmosphere, magnetosphere and extensive family of moons.'},
 Venus:{sub:'Terrestrial planet · Solar System',trust:'Verified Reality',source:'Astronomical catalogues & missions',facts:[['DAY','243 Earth days'],['TEMP','≈ 465°C avg'],['ATMOSPHERE','CO₂ dominant'],['MOONS','0']],summary:'A dense-atmosphere world for comparing planetary evolution with Earth.'},
 Mercury:{sub:'Terrestrial planet · Solar System',trust:'Verified Reality',source:'Astronomical catalogues & missions',facts:[['YEAR','88 Earth days'],['MOONS','0'],['DIAMETER','4,879 km'],['TYPE','Rocky planet']],summary:'The innermost planet, connected to solar physics, crater geology and planetary missions.'},
 'Active Volcanoes':{sub:'Global dynamic layer',trust:'Verified Reality',source:'Official hazard feeds · demo representation',facts:[['SCOPE','Global'],['TYPE','Live layer'],['FILTER','Active / recent'],['STATUS','Data connector ready']],summary:'A global dynamic layer designed to combine official event feeds with each volcano’s permanent knowledge node.'}
};
