// Stars
const sc=$('#stars'),sx=sc.getContext('2d');let stars=[];function resizeStars(){const d=Math.min(devicePixelRatio||1,2);sc.width=innerWidth*d;sc.height=innerHeight*d;sc.style.width=innerWidth+'px';sc.style.height=innerHeight+'px';sx.setTransform(d,0,0,d,0,0);stars=Array.from({length:Math.max(90,Math.floor(innerWidth*innerHeight/8200))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.2+Math.random()*1,a:.15+Math.random()*.55,s:.001+Math.random()*.002}))}function drawStars(t=0){sx.clearRect(0,0,innerWidth,innerHeight);for(const s of stars){sx.beginPath();sx.fillStyle=`rgba(187,210,225,${s.a*(.65+.35*Math.sin(t*s.s+s.x))})`;sx.arc(s.x,s.y,s.r,0,Math.PI*2);sx.fill()}requestAnimationFrame(drawStars)}resizeStars();drawStars();
// Procedural globe with draggable longitude and clickable projected markers
const ec=$('#earthCanvas'),ex=ec.getContext('2d');let W=0,H=0,D=1;const places=[{name:'Rome',lat:41.9,lon:12.5},{name:'Everest',lat:27.99,lon:86.93},{name:'Kīlauea',lat:19.42,lon:-155.29},{name:'Tokyo',lat:35.68,lon:139.65},{name:'New York',lat:40.71,lon:-74.0},{name:'Sydney',lat:-33.87,lon:151.21}];const landBlobs=[[50,-105,32,18],[7,-62,22,34],[51,15,36,20],[20,45,29,17],[5,25,20,24],[50,92,40,21],[-25,134,22,17],[66,-42,14,11]];
function resizeEarth(){const r=ec.getBoundingClientRect();D=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;ec.width=W*D;ec.height=H*D;ex.setTransform(D,0,0,D,0,0)}
function proj(lat,lon,R,cx,cy){const la=lat*Math.PI/180,lo=(lon+state.rot)*Math.PI/180,tilt=state.tilt*Math.PI/180;let x=Math.cos(la)*Math.sin(lo),y=Math.sin(la),z=Math.cos(la)*Math.cos(lo);const yy=y*Math.cos(tilt)-z*Math.sin(tilt),zz=y*Math.sin(tilt)+z*Math.cos(tilt);return{x:cx+R*x,y:cy-R*yy,z:zz}}
function ellipseBlob(lat,lon,rx,ry,R,cx,cy){const p=proj(lat,lon,R,cx,cy);if(p.z<-.15)return;const scale=.45+.55*Math.max(0,p.z);ex.save();ex.translate(p.x,p.y);ex.rotate((lon*.3)*Math.PI/180);ex.scale(Math.max(.15,scale),1);const g=ex.createRadialGradient(0,-ry*.25,2,0,0,rx);g.addColorStop(0,'#76967b');g.addColorStop(.55,'#426d5d');g.addColorStop(1,'#24453f');ex.fillStyle=g;ex.beginPath();ex.ellipse(0,0,rx*R/210,ry*R/210,0,0,Math.PI*2);ex.fill();ex.restore()}
function drawEarth(t=0){if(state.mode!=='earth'){requestAnimationFrame(drawEarth);return}ex.clearRect(0,0,W,H);const cx=W*.54,cy=H*.46,R=Math.min(W,H)*.34;let glow=ex.createRadialGradient(cx,cy,R*.75,cx,cy,R*1.38);glow.addColorStop(0,'rgba(44,142,151,.18)');glow.addColorStop(.55,'rgba(24,73,93,.08)');glow.addColorStop(1,'rgba(0,0,0,0)');ex.fillStyle=glow;ex.beginPath();ex.arc(cx,cy,R*1.4,0,Math.PI*2);ex.fill();const o=ex.createRadialGradient(cx-R*.27,cy-R*.32,R*.08,cx,cy,R);o.addColorStop(0,'#285f76');o.addColorStop(.42,'#103b56');o.addColorStop(.8,'#082136');o.addColorStop(1,'#020812');ex.fillStyle=o;ex.beginPath();ex.arc(cx,cy,R,0,Math.PI*2);ex.fill();ex.save();ex.beginPath();ex.arc(cx,cy,R,0,Math.PI*2);ex.clip();landBlobs.forEach(b=>ellipseBlob(...b,R,cx,cy));ex.strokeStyle='rgba(174,238,229,.09)';ex.lineWidth=1;for(let lat=-60;lat<=60;lat+=30){ex.beginPath();let started=false;for(let lon=-180;lon<=180;lon+=4){const p=proj(lat,lon,R,cx,cy);if(p.z>=0){if(!started){ex.moveTo(p.x,p.y);started=true}else ex.lineTo(p.x,p.y)}else started=false}ex.stroke()}for(let lon=-150;lon<=180;lon+=30){ex.beginPath();let started=false;for(let lat=-90;lat<=90;lat+=3){const p=proj(lat,lon,R,cx,cy);if(p.z>=0){if(!started){ex.moveTo(p.x,p.y);started=true}else ex.lineTo(p.x,p.y)}else started=false}ex.stroke()}const shine=ex.createLinearGradient(cx-R,cy-R,cx+R,cy+R);shine.addColorStop(0,'rgba(255,255,255,.13)');shine.addColorStop(.35,'rgba(255,255,255,.01)');shine.addColorStop(1,'rgba(0,0,0,.28)');ex.fillStyle=shine;ex.fillRect(cx-R,cy-R,R*2,R*2);ex.restore();ex.strokeStyle='rgba(98,224,199,.25)';ex.lineWidth=1.2;ex.beginPath();ex.arc(cx,cy,R+.5,0,Math.PI*2);ex.stroke();places.forEach(pl=>{const p=proj(pl.lat,pl.lon,R,cx,cy);if(p.z<.05)return;const pulse=3+1.2*Math.sin(t*.003+pl.lon);ex.fillStyle='#baffed';ex.beginPath();ex.arc(p.x,p.y,2,0,Math.PI*2);ex.fill();ex.strokeStyle='rgba(85,230,192,.45)';ex.beginPath();ex.arc(p.x,p.y,pulse,0,Math.PI*2);ex.stroke();ex.font='700 7px system-ui';ex.fillStyle='rgba(220,248,241,.78)';ex.fillText(pl.name.toUpperCase(),p.x+7,p.y-5)});if(!state.drag)state.rot+=.018;requestAnimationFrame(drawEarth)}
function focusEarth(name){const p=places.find(x=>x.name===name);if(!p)return;state.rot=-p.lon;toast(`Camera target: ${name}`)}
ec.addEventListener('pointerdown',e=>{state.drag=true;state.lastX=e.clientX;ec.setPointerCapture(e.pointerId)});ec.addEventListener('pointermove',e=>{if(!state.drag)return;state.rot+=(e.clientX-state.lastX)*.28;state.lastX=e.clientX});ec.addEventListener('pointerup',e=>{state.drag=false;ec.releasePointerCapture?.(e.pointerId)});ec.addEventListener('click',e=>{const r=ec.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,cx=W*.54,cy=H*.46,R=Math.min(W,H)*.34;let best=null,bd=18;for(const pl of places){const p=proj(pl.lat,pl.lon,R,cx,cy);if(p.z<.05)continue;const d=Math.hypot(p.x-mx,p.y-my);if(d<bd){bd=d;best=pl}}if(best)setFacts(best.name)});
addEventListener('resize',()=>{resizeStars();resizeEarth()});setFacts('Earth');resizeEarth();drawEarth();
