const $=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const lang=()=>{try{return localStorage.getItem('pv_language')||'it'}catch{return'it'}};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));

if(!window.__PV_DIRECTIONS_V1__){
 window.__PV_DIRECTIONS_V1__=true;
 let map=null,current=null,origin=null,mode='car',routeAbort=null;
 const style=document.createElement('style');
 style.textContent=`
 #pvDirections{position:fixed;left:14px;right:14px;bottom:calc(88px + env(safe-area-inset-bottom));z-index:2400;background:rgba(8,13,23,.96);border:1px solid rgba(255,255,255,.12);border-radius:22px;box-shadow:0 18px 50px rgba(0,0,0,.42);backdrop-filter:blur(16px);padding:14px;color:#fff;display:none;max-height:44vh;overflow:auto}#pvDirections.open{display:block}.pv-dir-head{display:flex;gap:10px;align-items:flex-start;justify-content:space-between}.pv-dir-head small{display:block;color:#72e8ff;font-size:10px;letter-spacing:.14em;font-weight:850;margin-bottom:4px}.pv-dir-head b{display:block;font-size:16px;line-height:1.25}.pv-dir-close{width:38px;height:38px;border-radius:12px;border:1px solid rgba(255,255,255,.12);background:#151c29;color:#fff;font-size:23px}.pv-dir-modes{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin:12px 0}.pv-dir-modes button{border:1px solid rgba(255,255,255,.1);background:#101725;color:#9eabc0;border-radius:12px;padding:10px 7px;font-weight:800}.pv-dir-modes button.active{color:#061018;background:#dffaff;border-color:#dffaff}.pv-dir-summary{display:flex;align-items:baseline;gap:10px;padding:11px 12px;border-radius:14px;background:#0a101b;border:1px solid rgba(255,255,255,.08)}.pv-dir-summary strong{font-size:22px}.pv-dir-summary span{font-size:13px;color:#a7b3c5}.pv-dir-status{font-size:12px;color:#8f9bae;margin:10px 2px}.pv-dir-steps{display:grid;gap:7px;margin-top:9px}.pv-dir-step{display:grid;grid-template-columns:26px 1fr;gap:8px;padding:8px 4px;border-top:1px solid rgba(255,255,255,.06);font-size:12px;color:#ced7e4}.pv-dir-step em{font-style:normal;color:#72e8ff}.pv-dir-external{display:block;text-align:center;margin-top:10px;padding:10px;border-radius:12px;background:#101725;border:1px solid rgba(255,255,255,.09);color:#dce8f6;text-decoration:none;font-weight:800;font-size:12px}@media(min-width:760px){#pvDirections{left:22px;right:auto;width:390px;bottom:22px;max-height:65vh}}
 `;document.head.appendChild(style);
 const panel=document.createElement('section');panel.id='pvDirections';panel.innerHTML='<div class="pv-dir-head"><div><small>PERKUSSUS · ROUTE</small><b id="pvDirTitle">Indicazioni</b></div><button class="pv-dir-close" id="pvDirClose">×</button></div><div class="pv-dir-modes"><button data-dir-mode="car">Auto</button><button data-dir-mode="foot">A piedi</button><button data-dir-mode="bike">Bici</button></div><div class="pv-dir-summary" id="pvDirSummary"><strong>—</strong><span>—</span></div><div class="pv-dir-status" id="pvDirStatus"></div><div class="pv-dir-steps" id="pvDirSteps"></div><a class="pv-dir-external" id="pvDirExternal" target="_blank" rel="noopener">Apri nel navigatore ↗</a>';document.body.appendChild(panel);
 const T=()=>lang()==='it'?{directions:'Indicazioni',car:'Auto',foot:'A piedi',bike:'Bici',position:'Cerco la tua posizione…',route:'Calcolo il percorso…',denied:'Non posso usare la posizione. Consenti la posizione al browser per le indicazioni interne.',failed:'Percorso non disponibile in questo momento.',min:'min',km:'km',external:'Apri nel navigatore ↗',depart:'Parti',arrive:'Arrivo a destinazione',continue:'Continua',turn:'Svolta',right:'a destra',left:'a sinistra',straight:'dritto'}:{directions:'Directions',car:'Car',foot:'Walk',bike:'Bike',position:'Getting your position…',route:'Calculating route…',denied:'Location is required for in-app directions.',failed:'Route is unavailable right now.',min:'min',km:'km',external:'Open in navigator ↗',depart:'Start',arrive:'Arrive at destination',continue:'Continue',turn:'Turn',right:'right',left:'left',straight:'straight'};
 function show(){const t=T();$('#pvDirTitle').textContent=current?.name||t.directions;$('#pvDirExternal').textContent=t.external;panel.classList.add('open');syncModes()}
 function close(){panel.classList.remove('open');routeAbort?.abort();clearRoute()}
 function syncModes(){const t=T();const labels={car:t.car,foot:t.foot,bike:t.bike};panel.querySelectorAll('[data-dir-mode]').forEach(b=>{b.textContent=labels[b.dataset.dirMode];b.classList.toggle('active',b.dataset.dirMode===mode)})}
 function setStatus(s){$('#pvDirStatus').textContent=s||''}
 function clearRoute(){if(!map)return;for(const id of ['pv-route-dest','pv-route-origin','pv-route-line','pv-route-casing'])try{if(map.getLayer(id))map.removeLayer(id)}catch{}try{if(map.getSource('pv-route'))map.removeSource('pv-route')}catch{}}
 function drawRoute(route){if(!map||!route?.geometry)return;clearRoute();const coords=route.geometry.coordinates,features=[{type:'Feature',properties:{kind:'route'},geometry:route.geometry},{type:'Feature',properties:{kind:'origin'},geometry:{type:'Point',coordinates:[origin.lon,origin.lat]}},{type:'Feature',properties:{kind:'destination'},geometry:{type:'Point',coordinates:[current.lon,current.lat]}}];try{map.addSource('pv-route',{type:'geojson',data:{type:'FeatureCollection',features}});map.addLayer({id:'pv-route-casing',type:'line',source:'pv-route',filter:['==',['get','kind'],'route'],paint:{'line-color':'#07101b','line-width':9,'line-opacity':.82}});map.addLayer({id:'pv-route-line',type:'line',source:'pv-route',filter:['==',['get','kind'],'route'],paint:{'line-color':'#72e8ff','line-width':5,'line-opacity':1}});map.addLayer({id:'pv-route-origin',type:'circle',source:'pv-route',filter:['==',['get','kind'],'origin'],paint:{'circle-radius':7,'circle-color':'#ffffff','circle-stroke-width':3,'circle-stroke-color':'#2bca8b'}});map.addLayer({id:'pv-route-dest',type:'circle',source:'pv-route',filter:['==',['get','kind'],'destination'],paint:{'circle-radius':7,'circle-color':'#ffffff','circle-stroke-width':3,'circle-stroke-color':'#72e8ff'}});let minX=Infinity,minY=Infinity,maxX=-Infinity,maxY=-Infinity;for(const c of coords){minX=Math.min(minX,c[0]);minY=Math.min(minY,c[1]);maxX=Math.max(maxX,c[0]);maxY=Math.max(maxY,c[1])}map.fitBounds([[minX,minY],[maxX,maxY]],{padding:{top:170,bottom:260,left:45,right:65},duration:650,maxZoom:17})}catch(e){console.warn('route draw',e)}}
 function instruction(step){const t=T(),m=step?.maneuver||{},name=step?.name?` · ${step.name}`:'';if(m.type==='depart')return t.depart+name;if(m.type==='arrive')return t.arrive;if(m.type==='turn'||m.type==='end of road'){const mod=/right/.test(m.modifier||'')?t.right:/left/.test(m.modifier||'')?t.left:t.straight;return`${t.turn} ${mod}${name}`}if(m.type==='continue'||m.type==='new name')return`${t.continue}${name}`;if(m.type==='roundabout'||m.type==='rotary')return`${t.continue} · rotatoria${name}`;return`${t.continue}${name}`}
 function showSteps(route){const steps=route?.legs?.flatMap(l=>l.steps||[])||[];$('#pvDirSteps').innerHTML=steps.slice(0,12).map((s,i)=>`<div class="pv-dir-step"><em>${i+1}</em><span>${esc(instruction(s))}</span></div>`).join('')}
 function endpoint(){if(mode==='foot')return'https://routing.openstreetmap.de/routed-foot/route/v1/driving/';if(mode==='bike')return'https://routing.openstreetmap.de/routed-bike/route/v1/driving/';return'https://router.project-osrm.org/route/v1/driving/'}
 async function route(){if(!origin||!current)return;const t=T();setStatus(t.route);routeAbort?.abort();routeAbort=new AbortController();const u=`${endpoint()}${origin.lon},${origin.lat};${current.lon},${current.lat}?overview=full&geometries=geojson&steps=true&alternatives=false`;try{const r=await fetch(u,{signal:routeAbort.signal,headers:{accept:'application/json'}});if(!r.ok)throw new Error(`route ${r.status}`);const j=await r.json(),best=j.routes?.[0];if(!best)throw new Error('no route');drawRoute(best);const km=best.distance/1000,min=Math.max(1,Math.round(best.duration/60));$('#pvDirSummary').innerHTML=`<strong>${min} ${t.min}</strong><span>${km<10?km.toFixed(1):Math.round(km)} ${t.km}</span>`;setStatus('');showSteps(best)}catch(e){if(e.name!=='AbortError')setStatus(t.failed)}}
 function locate(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('geolocation'));navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lon:p.coords.longitude}),reject,{enableHighAccuracy:false,timeout:6000,maximumAge:60000})})}
 async function start(dest){current=dest;mode='car';document.querySelector('#infoSheet')?.classList.remove('open');document.querySelector('#scrim')?.classList.remove('open');show();const t=T();setStatus(t.position);$('#pvDirSummary').innerHTML='<strong>—</strong><span>—</span>';$('#pvDirSteps').innerHTML='';$('#pvDirExternal').href=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${dest.lat},${dest.lon}`)}`;try{origin=await locate();await route()}catch{setStatus(t.denied)}}
 document.addEventListener('click',e=>{const a=e.target.closest?.('a.primary-link[href*="google.com/maps/dir"]');if(!a)return;const u=new URL(a.href),d=u.searchParams.get('destination')||'',m=d.match(/(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)/);if(!m)return;e.preventDefault();e.stopImmediatePropagation();start({lat:Number(m[1]),lon:Number(m[2]),name:$('#infoTitle')?.textContent?.trim()||T().directions})},true);
 panel.addEventListener('click',e=>{const b=e.target.closest?.('[data-dir-mode]');if(!b)return;mode=b.dataset.dirMode;syncModes();route()});$('#pvDirClose').addEventListener('click',close);
 async function init(){for(let i=0;i<180;i++){if(window.__PV_MAP__?.getStyle){map=window.__PV_MAP__;break}await sleep(50)}}init();
}
