(()=>{
'use strict';
const LANGS={
  it:{label:'Italiano',native:'Italiano',flag:'🇮🇹',locale:'it-IT',api:'it',wiki:'it'},
  en:{label:'English',native:'English',flag:'🇬🇧',locale:'en-US',api:'en',wiki:'en'},
  fr:{label:'Français',native:'Français',flag:'🇫🇷',locale:'fr-FR',api:'fr',wiki:'fr'},
  es:{label:'Español',native:'Español',flag:'🇪🇸',locale:'es-ES',api:'es',wiki:'es'},
  de:{label:'Deutsch',native:'Deutsch',flag:'🇩🇪',locale:'de-DE',api:'de',wiki:'de'},
  ru:{label:'Русский',native:'Русский',flag:'🇷🇺',locale:'ru-RU',api:'ru',wiki:'ru'},
  hi:{label:'Hindi',native:'हिन्दी',flag:'🇮🇳',locale:'hi-IN',api:'hi',wiki:'hi'},
  pt:{label:'Português',native:'Português',flag:'🇵🇹',locale:'pt-PT',api:'pt',wiki:'pt'},
  zh:{label:'Chinese',native:'简体中文',flag:'🇨🇳',locale:'zh-CN',api:'zh-CN',wiki:'zh'},
  ja:{label:'Japanese',native:'日本語',flag:'🇯🇵',locale:'ja-JP',api:'ja',wiki:'ja'}
};
const D={
it:{
search:'Cerca',layers:'Livelli',language:'Lingua',realEarth:'TERRA REALE',dataLoading:'OPENSTREETMAP · CARICAMENTO…',gesture:'Tocca un punto per info · trascina · pizzica per zoomare',retry:'RIPROVA',
liveEyebrow:'LIVE EARTH · DATI OPERATIVI',liveTitle:'Il pianeta mentre cambia.',liveCopy:'Solo feed realmente collegati, con fonte e aggiornamento dichiarati.',usgs24:'USGS · 24H',maxMagnitude:'MAGNITUDO MAX',quakesInFeed:'terremoti nel feed',waitingData:'in attesa dati',recentEvents:'Eventi recenti',tapEvent:'tocca un evento per localizzarlo',loadingUsgs:'Caricamento USGS…',
spaceTitle:'Spazio, senza dati inventati.',spaceCopy:'Il modulo Space verrà collegato a cataloghi e missioni reali.',spaceStatus:'Stato: interfaccia pronta · integrazione dati astronomici in sviluppo.',timeEyebrow:'TIME · REALITY REPLAY',timeTitle:'La stessa realtà, nel tempo.',timeCopy:'Archivi osservati, ricostruzioni scientifiche e simulazioni resteranno separati e dichiarati.',timeStatus:'Stato: interfaccia pronta · timeline scientifica in sviluppo.',
navEarth:'EARTH',navLive:'LIVE',navSpace:'SPACE',navTime:'TIME',navMore:'ALTRO',askGo:'ASK & GO',searchPlace:'Cerca un luogo reale',searchPlaceholder:'Roma, Everest, Tokyo…',go:'VAI',rome:'Roma',italy:'Italia',everest:'Everest',himalaya:'Himalaya',kilauea:'Kīlauea',hawaii:'Hawaiʻi',tokyo:'Tokyo',japan:'Giappone',
realityLayers:'REALITY LAYERS',earthViewTitle:'Come vuoi vedere la Terra',map:'MAPPA',satellite:'SATELLITE',labelsTitle:'Nomi di paesi, città e luoghi',labelsSub:'OpenStreetMap / OpenFreeMap',terrain3d:'Terreno 3D',terrainSub:'Modello digitale di elevazione Mapterhorn',buildings3d:'Edifici 3D',buildingsSub:'Quando disponibili nei dati OpenStreetMap',quakes:'Terremoti',quakesSub:'USGS · ultime 24 ore',satelliteNote:'La vista satellite usa immagini reali ma non è una ripresa live. La mappa vettoriale mostra strade, nomi e punti d’interesse a livelli di zoom progressivi.',
verifiedReality:'VERIFIED REALITY',information:'Informazioni',moreModules:'Altri moduli',sourcesTransparency:'Fonti & trasparenza',provenance:'Provenienza, data e licenze',missions:'Missions',inDevelopment:'In sviluppo',passport:'Passport',chooseLanguage:'Scegli la lingua',languageNote:'L’interfaccia, le schede informative e le fonti enciclopediche seguono la lingua scelta. I nomi geografici usano la traduzione disponibile; in assenza di una traduzione ufficiale resta il nome locale.',
loadingMapEngine:'Caricamento motore cartografico…',loadingVector:'Caricamento mappa vettoriale…',loadingVectorText:'Strade, città, confini e punti d’interesse da OpenStreetMap/OpenFreeMap.',fallbackMap:'Attivo la mappa di riserva…',fallbackText:'Il basemap vettoriale non ha risposto: uso OpenStreetMap raster.',addingEarth:'Aggiungo il modello della Terra…',addingEarthText:'Globo 3D, satellite e modello di elevazione.',connectingLive:'Collegamento dati live…',earthReady:'Terra pronta.',earthReadyText:'Mappa dettagliata, satellite, dati live e schede informative.',earthFailed:'La Terra non si è caricata.',cartoFailed:'I servizi cartografici non hanno risposto.',usgsUnavailable:'Feed USGS temporaneamente non raggiungibile. La mappa resta utilizzabile.',seismicEvent:'Evento sismico',depthLower:'profondità',magnitude:'Magnitudo',depth:'Profondità',coordinates:'Coordinate',verifiedSource:'Fonte verificata',usgsVerified:'USGS Earthquake Hazards Program · feed GeoJSON ufficiale delle ultime 24 ore.',inspector:'REALITY INSPECTOR',analyzing:'Analisi del punto…',querying:'Interrogo OpenStreetMap, Wikipedia/Wikidata e dati di elevazione…',pointEarth:'Punto sulla Terra',geoPosition:'Posizione geografica',verifiedPlace:'VERIFIED PLACE DATA',elevation:'Elevazione',terrainLanduse:'Terreno / uso suolo',osmCategory:'Categoria OSM',quickInfo:'Informazioni rapide',officialSite:'Sito ufficiale ↗',sources:'Fonti',sourcesText:'Posizione: OpenStreetMap/Nominatim. Terreno e superficie: OpenStreetMap/Overpass. Elevazione: Open-Meteo su Copernicus DEM. Sintesi: Wikipedia. Sito ufficiale: Wikidata P856 quando disponibile.',streetNote:'Street View si apre per ora nel servizio esterno. L’integrazione immersiva dentro Perkussus richiede una chiave Google Maps Platform o un token Mapillary con le relative condizioni d’uso.',notClassified:'Non classificato nei dati OSM',searching:'Ricerca…',noResults:'Nessun risultato',locating:'Cerco la posizione…',positionDenied:'Posizione non autorizzata',map2d:'Mappa 2D',globe3d:'Globo 3D',terrainOn:'Terreno 3D attivo',terrainOff:'Terreno 3D disattivato',satelliteUnavailable:'Satellite non disponibile'
},
en:{
search:'Search',layers:'Layers',language:'Language',realEarth:'REAL EARTH',dataLoading:'OPENSTREETMAP · LOADING…',gesture:'Tap a point for info · drag · pinch to zoom',retry:'RETRY',
liveEyebrow:'LIVE EARTH · OPERATIONAL DATA',liveTitle:'The planet as it changes.',liveCopy:'Only genuinely connected feeds, with source and update status clearly stated.',usgs24:'USGS · 24H',maxMagnitude:'MAX MAGNITUDE',quakesInFeed:'earthquakes in feed',waitingData:'waiting for data',recentEvents:'Recent events',tapEvent:'tap an event to locate it',loadingUsgs:'Loading USGS…',
spaceTitle:'Space, without invented data.',spaceCopy:'The Space module will be connected to real catalogues and missions.',spaceStatus:'Status: interface ready · astronomical data integration in development.',timeEyebrow:'TIME · REALITY REPLAY',timeTitle:'The same reality, through time.',timeCopy:'Observed archives, scientific reconstructions and simulations will remain separate and clearly identified.',timeStatus:'Status: interface ready · scientific timeline in development.',
navEarth:'EARTH',navLive:'LIVE',navSpace:'SPACE',navTime:'TIME',navMore:'MORE',askGo:'ASK & GO',searchPlace:'Search a real place',searchPlaceholder:'Rome, Everest, Tokyo…',go:'GO',rome:'Rome',italy:'Italy',everest:'Everest',himalaya:'Himalayas',kilauea:'Kīlauea',hawaii:'Hawaiʻi',tokyo:'Tokyo',japan:'Japan',
realityLayers:'REALITY LAYERS',earthViewTitle:'Choose how to view Earth',map:'MAP',satellite:'SATELLITE',labelsTitle:'Country, city and place names',labelsSub:'OpenStreetMap / OpenFreeMap',terrain3d:'3D terrain',terrainSub:'Mapterhorn digital elevation model',buildings3d:'3D buildings',buildingsSub:'Where available in OpenStreetMap data',quakes:'Earthquakes',quakesSub:'USGS · last 24 hours',satelliteNote:'Satellite view uses real imagery, but it is not a live feed. The vector map reveals roads, names and points of interest progressively as you zoom in.',
verifiedReality:'VERIFIED REALITY',information:'Information',moreModules:'More modules',sourcesTransparency:'Sources & transparency',provenance:'Provenance, date and licences',missions:'Missions',inDevelopment:'In development',passport:'Passport',chooseLanguage:'Choose language',languageNote:'The interface, information cards and encyclopaedic sources follow your selected language. Geographic names use an available translation; where no official translation exists, the local name is retained.',
loadingMapEngine:'Loading map engine…',loadingVector:'Loading vector map…',loadingVectorText:'Roads, cities, borders and points of interest from OpenStreetMap/OpenFreeMap.',fallbackMap:'Starting fallback map…',fallbackText:'The vector basemap did not respond; using OpenStreetMap raster tiles.',addingEarth:'Adding the Earth model…',addingEarthText:'3D globe, satellite imagery and elevation model.',connectingLive:'Connecting live data…',earthReady:'Earth ready.',earthReadyText:'Detailed map, satellite imagery, live data and information cards.',earthFailed:'Earth could not be loaded.',cartoFailed:'The mapping services did not respond.',usgsUnavailable:'The USGS feed is temporarily unavailable. The map remains usable.',seismicEvent:'Seismic event',depthLower:'depth',magnitude:'Magnitude',depth:'Depth',coordinates:'Coordinates',verifiedSource:'Verified source',usgsVerified:'USGS Earthquake Hazards Program · official GeoJSON feed for the last 24 hours.',inspector:'REALITY INSPECTOR',analyzing:'Analysing point…',querying:'Querying OpenStreetMap, Wikipedia/Wikidata and elevation data…',pointEarth:'Point on Earth',geoPosition:'Geographic position',verifiedPlace:'VERIFIED PLACE DATA',elevation:'Elevation',terrainLanduse:'Terrain / land use',osmCategory:'OSM category',quickInfo:'Quick information',officialSite:'Official site ↗',sources:'Sources',sourcesText:'Position: OpenStreetMap/Nominatim. Terrain and surface: OpenStreetMap/Overpass. Elevation: Open-Meteo using Copernicus DEM. Summary: Wikipedia. Official website: Wikidata P856 when available.',streetNote:'Street View currently opens in the external service. Immersive integration inside Perkussus requires a Google Maps Platform key or a Mapillary token, subject to their terms of use.',notClassified:'Not classified in OSM data',searching:'Searching…',noResults:'No results',locating:'Finding your location…',positionDenied:'Location permission denied',map2d:'2D map',globe3d:'3D globe',terrainOn:'3D terrain on',terrainOff:'3D terrain off',satelliteUnavailable:'Satellite unavailable'
},
fr:{
search:'Rechercher',layers:'Calques',language:'Langue',realEarth:'TERRE RÉELLE',dataLoading:'OPENSTREETMAP · CHARGEMENT…',gesture:'Touchez un point pour les infos · faites glisser · pincez pour zoomer',retry:'RÉESSAYER',
liveEyebrow:'TERRE EN DIRECT · DONNÉES OPÉRATIONNELLES',liveTitle:'La planète en évolution.',liveCopy:'Uniquement des flux réellement connectés, avec source et mise à jour clairement indiquées.',usgs24:'USGS · 24 H',maxMagnitude:'MAGNITUDE MAX',quakesInFeed:'séismes dans le flux',waitingData:'en attente de données',recentEvents:'Événements récents',tapEvent:'touchez un événement pour le localiser',loadingUsgs:'Chargement USGS…',
spaceTitle:'L’espace, sans données inventées.',spaceCopy:'Le module Space sera relié à des catalogues et missions réels.',spaceStatus:'État : interface prête · intégration des données astronomiques en développement.',timeEyebrow:'TEMPS · REALITY REPLAY',timeTitle:'La même réalité, à travers le temps.',timeCopy:'Archives observées, reconstructions scientifiques et simulations resteront séparées et clairement identifiées.',timeStatus:'État : interface prête · frise scientifique en développement.',
navEarth:'TERRE',navLive:'DIRECT',navSpace:'ESPACE',navTime:'TEMPS',navMore:'PLUS',askGo:'DEMANDER & ALLER',searchPlace:'Rechercher un lieu réel',searchPlaceholder:'Rome, Everest, Tokyo…',go:'ALLER',rome:'Rome',italy:'Italie',everest:'Everest',himalaya:'Himalaya',kilauea:'Kīlauea',hawaii:'Hawaï',tokyo:'Tokyo',japan:'Japon',
realityLayers:'CALQUES DE RÉALITÉ',earthViewTitle:'Choisissez comment voir la Terre',map:'CARTE',satellite:'SATELLITE',labelsTitle:'Noms des pays, villes et lieux',labelsSub:'OpenStreetMap / OpenFreeMap',terrain3d:'Relief 3D',terrainSub:'Modèle numérique d’élévation Mapterhorn',buildings3d:'Bâtiments 3D',buildingsSub:'Lorsqu’ils sont disponibles dans OpenStreetMap',quakes:'Séismes',quakesSub:'USGS · dernières 24 heures',satelliteNote:'La vue satellite utilise des images réelles, mais ce n’est pas un flux en direct. La carte vectorielle révèle progressivement routes, noms et points d’intérêt en zoomant.',
verifiedReality:'RÉALITÉ VÉRIFIÉE',information:'Informations',moreModules:'Autres modules',sourcesTransparency:'Sources & transparence',provenance:'Provenance, date et licences',missions:'Missions',inDevelopment:'En développement',passport:'Passeport',chooseLanguage:'Choisir la langue',languageNote:'L’interface, les fiches d’information et les sources encyclopédiques suivent la langue choisie. Les noms géographiques utilisent une traduction disponible ; sans traduction officielle, le nom local est conservé.',
loadingMapEngine:'Chargement du moteur cartographique…',loadingVector:'Chargement de la carte vectorielle…',loadingVectorText:'Routes, villes, frontières et points d’intérêt depuis OpenStreetMap/OpenFreeMap.',fallbackMap:'Activation de la carte de secours…',fallbackText:'Le fond vectoriel n’a pas répondu ; utilisation des tuiles raster OpenStreetMap.',addingEarth:'Ajout du modèle terrestre…',addingEarthText:'Globe 3D, imagerie satellite et modèle d’élévation.',connectingLive:'Connexion des données en direct…',earthReady:'Terre prête.',earthReadyText:'Carte détaillée, satellite, données en direct et fiches d’information.',earthFailed:'La Terre n’a pas pu être chargée.',cartoFailed:'Les services cartographiques n’ont pas répondu.',usgsUnavailable:'Le flux USGS est temporairement indisponible. La carte reste utilisable.',seismicEvent:'Événement sismique',depthLower:'profondeur',magnitude:'Magnitude',depth:'Profondeur',coordinates:'Coordonnées',verifiedSource:'Source vérifiée',usgsVerified:'USGS Earthquake Hazards Program · flux GeoJSON officiel des dernières 24 heures.',inspector:'INSPECTEUR DE RÉALITÉ',analyzing:'Analyse du point…',querying:'Interrogation d’OpenStreetMap, Wikipedia/Wikidata et des données d’altitude…',pointEarth:'Point sur Terre',geoPosition:'Position géographique',verifiedPlace:'DONNÉES DE LIEU VÉRIFIÉES',elevation:'Altitude',terrainLanduse:'Terrain / usage du sol',osmCategory:'Catégorie OSM',quickInfo:'Informations rapides',officialSite:'Site officiel ↗',sources:'Sources',sourcesText:'Position : OpenStreetMap/Nominatim. Terrain et surface : OpenStreetMap/Overpass. Altitude : Open-Meteo sur Copernicus DEM. Synthèse : Wikipédia. Site officiel : Wikidata P856 lorsqu’il est disponible.',streetNote:'Street View s’ouvre pour l’instant dans le service externe. L’intégration immersive dans Perkussus nécessite une clé Google Maps Platform ou un jeton Mapillary, selon leurs conditions d’utilisation.',notClassified:'Non classé dans les données OSM',searching:'Recherche…',noResults:'Aucun résultat',locating:'Recherche de votre position…',positionDenied:'Accès à la position refusé',map2d:'Carte 2D',globe3d:'Globe 3D',terrainOn:'Relief 3D activé',terrainOff:'Relief 3D désactivé',satelliteUnavailable:'Satellite indisponible'
},
es:{
search:'Buscar',layers:'Capas',language:'Idioma',realEarth:'TIERRA REAL',dataLoading:'OPENSTREETMAP · CARGANDO…',gesture:'Toca un punto para ver información · arrastra · pellizca para acercar',retry:'REINTENTAR',
liveEyebrow:'TIERRA EN VIVO · DATOS OPERATIVOS',liveTitle:'El planeta mientras cambia.',liveCopy:'Solo fuentes realmente conectadas, con origen y actualización claramente indicados.',usgs24:'USGS · 24 H',maxMagnitude:'MAGNITUD MÁX',quakesInFeed:'terremotos en el feed',waitingData:'esperando datos',recentEvents:'Eventos recientes',tapEvent:'toca un evento para localizarlo',loadingUsgs:'Cargando USGS…',
spaceTitle:'El espacio, sin datos inventados.',spaceCopy:'El módulo Space se conectará a catálogos y misiones reales.',spaceStatus:'Estado: interfaz lista · integración de datos astronómicos en desarrollo.',timeEyebrow:'TIEMPO · REALITY REPLAY',timeTitle:'La misma realidad, a través del tiempo.',timeCopy:'Archivos observados, reconstrucciones científicas y simulaciones permanecerán separados y claramente identificados.',timeStatus:'Estado: interfaz lista · cronología científica en desarrollo.',
navEarth:'TIERRA',navLive:'EN VIVO',navSpace:'ESPACIO',navTime:'TIEMPO',navMore:'MÁS',askGo:'PREGUNTA & VE',searchPlace:'Buscar un lugar real',searchPlaceholder:'Roma, Everest, Tokio…',go:'IR',rome:'Roma',italy:'Italia',everest:'Everest',himalaya:'Himalaya',kilauea:'Kīlauea',hawaii:'Hawái',tokyo:'Tokio',japan:'Japón',
realityLayers:'CAPAS DE REALIDAD',earthViewTitle:'Elige cómo ver la Tierra',map:'MAPA',satellite:'SATÉLITE',labelsTitle:'Nombres de países, ciudades y lugares',labelsSub:'OpenStreetMap / OpenFreeMap',terrain3d:'Terreno 3D',terrainSub:'Modelo digital de elevación Mapterhorn',buildings3d:'Edificios 3D',buildingsSub:'Cuando estén disponibles en los datos de OpenStreetMap',quakes:'Terremotos',quakesSub:'USGS · últimas 24 horas',satelliteNote:'La vista satelital utiliza imágenes reales, pero no es una transmisión en vivo. El mapa vectorial muestra progresivamente carreteras, nombres y puntos de interés al acercar.',
verifiedReality:'REALIDAD VERIFICADA',information:'Información',moreModules:'Más módulos',sourcesTransparency:'Fuentes y transparencia',provenance:'Procedencia, fecha y licencias',missions:'Misiones',inDevelopment:'En desarrollo',passport:'Pasaporte',chooseLanguage:'Elegir idioma',languageNote:'La interfaz, las fichas informativas y las fuentes enciclopédicas siguen el idioma elegido. Los nombres geográficos usan una traducción disponible; si no existe una traducción oficial, se conserva el nombre local.',
loadingMapEngine:'Cargando motor cartográfico…',loadingVector:'Cargando mapa vectorial…',loadingVectorText:'Carreteras, ciudades, fronteras y puntos de interés de OpenStreetMap/OpenFreeMap.',fallbackMap:'Activando mapa de respaldo…',fallbackText:'El mapa base vectorial no respondió; se usan teselas raster de OpenStreetMap.',addingEarth:'Añadiendo el modelo de la Tierra…',addingEarthText:'Globo 3D, imágenes satelitales y modelo de elevación.',connectingLive:'Conectando datos en vivo…',earthReady:'Tierra lista.',earthReadyText:'Mapa detallado, satélite, datos en vivo y fichas informativas.',earthFailed:'No se pudo cargar la Tierra.',cartoFailed:'Los servicios cartográficos no respondieron.',usgsUnavailable:'El feed de USGS no está disponible temporalmente. El mapa sigue siendo utilizable.',seismicEvent:'Evento sísmico',depthLower:'profundidad',magnitude:'Magnitud',depth:'Profundidad',coordinates:'Coordenadas',verifiedSource:'Fuente verificada',usgsVerified:'USGS Earthquake Hazards Program · feed GeoJSON oficial de las últimas 24 horas.',inspector:'INSPECTOR DE REALIDAD',analyzing:'Analizando el punto…',querying:'Consultando OpenStreetMap, Wikipedia/Wikidata y datos de elevación…',pointEarth:'Punto en la Tierra',geoPosition:'Posición geográfica',verifiedPlace:'DATOS DEL LUGAR VERIFICADOS',elevation:'Elevación',terrainLanduse:'Terreno / uso del suelo',osmCategory:'Categoría OSM',quickInfo:'Información rápida',officialSite:'Sitio oficial ↗',sources:'Fuentes',sourcesText:'Posición: OpenStreetMap/Nominatim. Terreno y superficie: OpenStreetMap/Overpass. Elevación: Open-Meteo sobre Copernicus DEM. Resumen: Wikipedia. Sitio oficial: Wikidata P856 cuando esté disponible.',streetNote:'Street View se abre por ahora en el servicio externo. La integración inmersiva dentro de Perkussus requiere una clave de Google Maps Platform o un token de Mapillary, sujetos a sus condiciones de uso.',notClassified:'No clasificado en los datos OSM',searching:'Buscando…',noResults:'Sin resultados',locating:'Buscando tu ubicación…',positionDenied:'Permiso de ubicación denegado',map2d:'Mapa 2D',globe3d:'Globo 3D',terrainOn:'Terreno 3D activado',terrainOff:'Terreno 3D desactivado',satelliteUnavailable:'Satélite no disponible'
},
de:{
search:'Suchen',layers:'Ebenen',language:'Sprache',realEarth:'ECHTE ERDE',dataLoading:'OPENSTREETMAP · WIRD GELADEN…',gesture:'Punkt antippen für Infos · ziehen · mit zwei Fingern zoomen',retry:'ERNEUT VERSUCHEN',
liveEyebrow:'LIVE EARTH · BETRIEBSDATEN',liveTitle:'Der Planet im Wandel.',liveCopy:'Nur tatsächlich verbundene Datenfeeds, mit klar ausgewiesener Quelle und Aktualisierung.',usgs24:'USGS · 24 STD.',maxMagnitude:'MAX. MAGNITUDE',quakesInFeed:'Erdbeben im Feed',waitingData:'warte auf Daten',recentEvents:'Aktuelle Ereignisse',tapEvent:'Ereignis antippen, um es zu lokalisieren',loadingUsgs:'USGS wird geladen…',
spaceTitle:'Weltraum, ohne erfundene Daten.',spaceCopy:'Das Space-Modul wird mit realen Katalogen und Missionen verbunden.',spaceStatus:'Status: Oberfläche bereit · astronomische Datenintegration in Entwicklung.',timeEyebrow:'ZEIT · REALITY REPLAY',timeTitle:'Dieselbe Realität im Lauf der Zeit.',timeCopy:'Beobachtete Archive, wissenschaftliche Rekonstruktionen und Simulationen bleiben getrennt und klar gekennzeichnet.',timeStatus:'Status: Oberfläche bereit · wissenschaftliche Zeitleiste in Entwicklung.',
navEarth:'ERDE',navLive:'LIVE',navSpace:'WELTRAUM',navTime:'ZEIT',navMore:'MEHR',askGo:'FRAGEN & LOS',searchPlace:'Einen realen Ort suchen',searchPlaceholder:'Rom, Everest, Tokio…',go:'LOS',rome:'Rom',italy:'Italien',everest:'Everest',himalaya:'Himalaya',kilauea:'Kīlauea',hawaii:'Hawaii',tokyo:'Tokio',japan:'Japan',
realityLayers:'REALITÄTSEBENEN',earthViewTitle:'Wie möchtest du die Erde sehen?',map:'KARTE',satellite:'SATELLIT',labelsTitle:'Namen von Ländern, Städten und Orten',labelsSub:'OpenStreetMap / OpenFreeMap',terrain3d:'3D-Gelände',terrainSub:'Digitales Höhenmodell Mapterhorn',buildings3d:'3D-Gebäude',buildingsSub:'Wenn in OpenStreetMap-Daten verfügbar',quakes:'Erdbeben',quakesSub:'USGS · letzte 24 Stunden',satelliteNote:'Die Satellitenansicht verwendet reale Bilder, ist aber kein Live-Feed. Die Vektorkarte zeigt beim Hineinzoomen schrittweise Straßen, Namen und Sehenswürdigkeiten.',
verifiedReality:'VERIFIZIERTE REALITÄT',information:'Informationen',moreModules:'Weitere Module',sourcesTransparency:'Quellen & Transparenz',provenance:'Herkunft, Datum und Lizenzen',missions:'Missionen',inDevelopment:'In Entwicklung',passport:'Pass',chooseLanguage:'Sprache wählen',languageNote:'Oberfläche, Informationskarten und enzyklopädische Quellen folgen der gewählten Sprache. Geografische Namen verwenden eine verfügbare Übersetzung; wenn keine offizielle Übersetzung existiert, bleibt der lokale Name erhalten.',
loadingMapEngine:'Kartensystem wird geladen…',loadingVector:'Vektorkarte wird geladen…',loadingVectorText:'Straßen, Städte, Grenzen und Sehenswürdigkeiten aus OpenStreetMap/OpenFreeMap.',fallbackMap:'Ersatzkarte wird gestartet…',fallbackText:'Die Vektorgrundkarte antwortete nicht; OpenStreetMap-Rasterkacheln werden verwendet.',addingEarth:'Erdmodell wird hinzugefügt…',addingEarthText:'3D-Globus, Satellitenbilder und Höhenmodell.',connectingLive:'Live-Daten werden verbunden…',earthReady:'Erde bereit.',earthReadyText:'Detaillierte Karte, Satellit, Live-Daten und Informationskarten.',earthFailed:'Die Erde konnte nicht geladen werden.',cartoFailed:'Die Kartendienste haben nicht geantwortet.',usgsUnavailable:'Der USGS-Feed ist vorübergehend nicht verfügbar. Die Karte bleibt nutzbar.',seismicEvent:'Seismisches Ereignis',depthLower:'Tiefe',magnitude:'Magnitude',depth:'Tiefe',coordinates:'Koordinaten',verifiedSource:'Verifizierte Quelle',usgsVerified:'USGS Earthquake Hazards Program · offizieller GeoJSON-Feed der letzten 24 Stunden.',inspector:'REALITÄTSINSPEKTOR',analyzing:'Punkt wird analysiert…',querying:'OpenStreetMap, Wikipedia/Wikidata und Höhendaten werden abgefragt…',pointEarth:'Punkt auf der Erde',geoPosition:'Geografische Position',verifiedPlace:'VERIFIZIERTE ORTSDATEN',elevation:'Höhe',terrainLanduse:'Gelände / Landnutzung',osmCategory:'OSM-Kategorie',quickInfo:'Kurzinformation',officialSite:'Offizielle Website ↗',sources:'Quellen',sourcesText:'Position: OpenStreetMap/Nominatim. Gelände und Oberfläche: OpenStreetMap/Overpass. Höhe: Open-Meteo auf Basis des Copernicus DEM. Zusammenfassung: Wikipedia. Offizielle Website: Wikidata P856, sofern verfügbar.',streetNote:'Street View wird derzeit im externen Dienst geöffnet. Für die immersive Integration in Perkussus ist ein Google-Maps-Platform-Schlüssel oder ein Mapillary-Token gemäß den jeweiligen Nutzungsbedingungen erforderlich.',notClassified:'In OSM-Daten nicht klassifiziert',searching:'Suche…',noResults:'Keine Ergebnisse',locating:'Position wird ermittelt…',positionDenied:'Standortzugriff verweigert',map2d:'2D-Karte',globe3d:'3D-Globus',terrainOn:'3D-Gelände aktiviert',terrainOff:'3D-Gelände deaktiviert',satelliteUnavailable:'Satellit nicht verfügbar'
},
ru:{
search:'Поиск',layers:'Слои',language:'Язык',realEarth:'РЕАЛЬНАЯ ЗЕМЛЯ',dataLoading:'OPENSTREETMAP · ЗАГРУЗКА…',gesture:'Нажмите точку для информации · перетаскивайте · разводите пальцы для масштаба',retry:'ПОВТОРИТЬ',
liveEyebrow:'ЗЕМЛЯ В РЕАЛЬНОМ ВРЕМЕНИ · ОПЕРАТИВНЫЕ ДАННЫЕ',liveTitle:'Планета в процессе изменений.',liveCopy:'Только реально подключённые источники с явно указанными происхождением и обновлением.',usgs24:'USGS · 24 Ч',maxMagnitude:'МАКС. МАГНИТУДА',quakesInFeed:'землетрясений в ленте',waitingData:'ожидание данных',recentEvents:'Недавние события',tapEvent:'нажмите событие, чтобы найти его на карте',loadingUsgs:'Загрузка USGS…',
spaceTitle:'Космос без вымышленных данных.',spaceCopy:'Модуль Space будет подключён к реальным каталогам и миссиям.',spaceStatus:'Статус: интерфейс готов · интеграция астрономических данных в разработке.',timeEyebrow:'ВРЕМЯ · REALITY REPLAY',timeTitle:'Одна и та же реальность во времени.',timeCopy:'Наблюдаемые архивы, научные реконструкции и симуляции будут разделены и чётко обозначены.',timeStatus:'Статус: интерфейс готов · научная временная шкала в разработке.',
navEarth:'ЗЕМЛЯ',navLive:'LIVE',navSpace:'КОСМОС',navTime:'ВРЕМЯ',navMore:'ЕЩЁ',askGo:'СПРОСИТЬ И ПЕРЕЙТИ',searchPlace:'Найти реальное место',searchPlaceholder:'Рим, Эверест, Токио…',go:'ПЕРЕЙТИ',rome:'Рим',italy:'Италия',everest:'Эверест',himalaya:'Гималаи',kilauea:'Килауэа',hawaii:'Гавайи',tokyo:'Токио',japan:'Япония',
realityLayers:'СЛОИ РЕАЛЬНОСТИ',earthViewTitle:'Как вы хотите видеть Землю',map:'КАРТА',satellite:'СПУТНИК',labelsTitle:'Названия стран, городов и мест',labelsSub:'OpenStreetMap / OpenFreeMap',terrain3d:'3D-рельеф',terrainSub:'Цифровая модель высот Mapterhorn',buildings3d:'3D-здания',buildingsSub:'Если доступны в данных OpenStreetMap',quakes:'Землетрясения',quakesSub:'USGS · последние 24 часа',satelliteNote:'Спутниковый режим использует реальные снимки, но не является прямой трансляцией. Векторная карта по мере масштабирования показывает дороги, названия и объекты интереса.',
verifiedReality:'ПРОВЕРЕННАЯ РЕАЛЬНОСТЬ',information:'Информация',moreModules:'Другие модули',sourcesTransparency:'Источники и прозрачность',provenance:'Происхождение, дата и лицензии',missions:'Миссии',inDevelopment:'В разработке',passport:'Паспорт',chooseLanguage:'Выберите язык',languageNote:'Интерфейс, информационные карточки и энциклопедические источники используют выбранный язык. Географические названия отображаются в доступном переводе; если официального перевода нет, сохраняется местное название.',
loadingMapEngine:'Загрузка картографического движка…',loadingVector:'Загрузка векторной карты…',loadingVectorText:'Дороги, города, границы и объекты интереса из OpenStreetMap/OpenFreeMap.',fallbackMap:'Запуск резервной карты…',fallbackText:'Векторная подложка не ответила; используются растровые тайлы OpenStreetMap.',addingEarth:'Добавление модели Земли…',addingEarthText:'3D-глобус, спутниковые снимки и модель высот.',connectingLive:'Подключение данных в реальном времени…',earthReady:'Земля готова.',earthReadyText:'Подробная карта, спутник, живые данные и информационные карточки.',earthFailed:'Не удалось загрузить Землю.',cartoFailed:'Картографические сервисы не ответили.',usgsUnavailable:'Лента USGS временно недоступна. Карта остаётся доступной.',seismicEvent:'Сейсмическое событие',depthLower:'глубина',magnitude:'Магнитуда',depth:'Глубина',coordinates:'Координаты',verifiedSource:'Проверенный источник',usgsVerified:'USGS Earthquake Hazards Program · официальный GeoJSON-поток за последние 24 часа.',inspector:'ИНСПЕКТОР РЕАЛЬНОСТИ',analyzing:'Анализ точки…',querying:'Запрос OpenStreetMap, Wikipedia/Wikidata и данных высот…',pointEarth:'Точка на Земле',geoPosition:'Географическое положение',verifiedPlace:'ПРОВЕРЕННЫЕ ДАННЫЕ О МЕСТЕ',elevation:'Высота',terrainLanduse:'Рельеф / землепользование',osmCategory:'Категория OSM',quickInfo:'Краткая информация',officialSite:'Официальный сайт ↗',sources:'Источники',sourcesText:'Положение: OpenStreetMap/Nominatim. Рельеф и поверхность: OpenStreetMap/Overpass. Высота: Open-Meteo на основе Copernicus DEM. Сводка: Wikipedia. Официальный сайт: Wikidata P856 при наличии.',streetNote:'Street View пока открывается во внешнем сервисе. Для иммерсивной интеграции внутри Perkussus требуется ключ Google Maps Platform или токен Mapillary с соблюдением их условий использования.',notClassified:'Не классифицировано в данных OSM',searching:'Поиск…',noResults:'Ничего не найдено',locating:'Определение местоположения…',positionDenied:'Доступ к местоположению запрещён',map2d:'2D-карта',globe3d:'3D-глобус',terrainOn:'3D-рельеф включён',terrainOff:'3D-рельеф выключен',satelliteUnavailable:'Спутник недоступен'
},
hi:{
search:'खोजें',layers:'परतें',language:'भाषा',realEarth:'वास्तविक पृथ्वी',dataLoading:'OPENSTREETMAP · लोड हो रहा है…',gesture:'जानकारी के लिए किसी बिंदु पर टैप करें · खींचें · ज़ूम के लिए पिंच करें',retry:'फिर कोशिश करें',
liveEyebrow:'लाइव अर्थ · परिचालन डेटा',liveTitle:'बदलती हुई पृथ्वी।',liveCopy:'केवल वास्तविक रूप से जुड़े डेटा फ़ीड, जिनका स्रोत और अद्यतन स्पष्ट रूप से बताया गया है।',usgs24:'USGS · 24 घंटे',maxMagnitude:'अधिकतम तीव्रता',quakesInFeed:'फ़ीड में भूकंप',waitingData:'डेटा की प्रतीक्षा',recentEvents:'हाल की घटनाएँ',tapEvent:'स्थान देखने के लिए घटना पर टैप करें',loadingUsgs:'USGS लोड हो रहा है…',
spaceTitle:'अंतरिक्ष, बिना गढ़े हुए डेटा के।',spaceCopy:'Space मॉड्यूल को वास्तविक कैटलॉग और मिशनों से जोड़ा जाएगा।',spaceStatus:'स्थिति: इंटरफ़ेस तैयार · खगोलीय डेटा एकीकरण विकासाधीन।',timeEyebrow:'समय · REALITY REPLAY',timeTitle:'एक ही वास्तविकता, समय के साथ।',timeCopy:'देखे गए अभिलेख, वैज्ञानिक पुनर्निर्माण और सिमुलेशन अलग और स्पष्ट रूप से चिह्नित रहेंगे।',timeStatus:'स्थिति: इंटरफ़ेस तैयार · वैज्ञानिक समयरेखा विकासाधीन।',
navEarth:'पृथ्वी',navLive:'लाइव',navSpace:'अंतरिक्ष',navTime:'समय',navMore:'और',askGo:'पूछें और जाएँ',searchPlace:'वास्तविक स्थान खोजें',searchPlaceholder:'रोम, एवरेस्ट, टोक्यो…',go:'जाएँ',rome:'रोम',italy:'इटली',everest:'एवरेस्ट',himalaya:'हिमालय',kilauea:'किलाउएआ',hawaii:'हवाई',tokyo:'टोक्यो',japan:'जापान',
realityLayers:'रियलिटी लेयर्स',earthViewTitle:'पृथ्वी को कैसे देखना है चुनें',map:'मानचित्र',satellite:'उपग्रह',labelsTitle:'देश, शहर और स्थानों के नाम',labelsSub:'OpenStreetMap / OpenFreeMap',terrain3d:'3D भू-भाग',terrainSub:'Mapterhorn डिजिटल ऊँचाई मॉडल',buildings3d:'3D इमारतें',buildingsSub:'जहाँ OpenStreetMap डेटा में उपलब्ध हों',quakes:'भूकंप',quakesSub:'USGS · पिछले 24 घंटे',satelliteNote:'उपग्रह दृश्य वास्तविक चित्रों का उपयोग करता है, लेकिन यह लाइव प्रसारण नहीं है। ज़ूम करने पर वेक्टर मानचित्र सड़कों, नामों और रुचि के स्थानों को क्रमशः दिखाता है।',
verifiedReality:'सत्यापित वास्तविकता',information:'जानकारी',moreModules:'अन्य मॉड्यूल',sourcesTransparency:'स्रोत और पारदर्शिता',provenance:'उत्पत्ति, तारीख और लाइसेंस',missions:'मिशन',inDevelopment:'विकासाधीन',passport:'पासपोर्ट',chooseLanguage:'भाषा चुनें',languageNote:'इंटरफ़ेस, जानकारी कार्ड और विश्वकोश स्रोत चुनी गई भाषा का उपयोग करते हैं। भौगोलिक नाम उपलब्ध अनुवाद में दिखते हैं; आधिकारिक अनुवाद न होने पर स्थानीय नाम रखा जाता है।',
loadingMapEngine:'मानचित्र इंजन लोड हो रहा है…',loadingVector:'वेक्टर मानचित्र लोड हो रहा है…',loadingVectorText:'OpenStreetMap/OpenFreeMap से सड़कें, शहर, सीमाएँ और रुचि के स्थान।',fallbackMap:'बैकअप मानचित्र शुरू हो रहा है…',fallbackText:'वेक्टर बेसमैप ने उत्तर नहीं दिया; OpenStreetMap रास्टर टाइलों का उपयोग किया जा रहा है।',addingEarth:'पृथ्वी मॉडल जोड़ा जा रहा है…',addingEarthText:'3D ग्लोब, उपग्रह चित्र और ऊँचाई मॉडल।',connectingLive:'लाइव डेटा जोड़ा जा रहा है…',earthReady:'पृथ्वी तैयार है।',earthReadyText:'विस्तृत मानचित्र, उपग्रह चित्र, लाइव डेटा और जानकारी कार्ड।',earthFailed:'पृथ्वी लोड नहीं हो सकी।',cartoFailed:'मानचित्र सेवाओं ने उत्तर नहीं दिया।',usgsUnavailable:'USGS फ़ीड अस्थायी रूप से उपलब्ध नहीं है। मानचित्र फिर भी उपयोग किया जा सकता है।',seismicEvent:'भूकंपीय घटना',depthLower:'गहराई',magnitude:'तीव्रता',depth:'गहराई',coordinates:'निर्देशांक',verifiedSource:'सत्यापित स्रोत',usgsVerified:'USGS Earthquake Hazards Program · पिछले 24 घंटों का आधिकारिक GeoJSON फ़ीड।',inspector:'रियलिटी इंस्पेक्टर',analyzing:'बिंदु का विश्लेषण…',querying:'OpenStreetMap, Wikipedia/Wikidata और ऊँचाई डेटा से जानकारी ली जा रही है…',pointEarth:'पृथ्वी पर बिंदु',geoPosition:'भौगोलिक स्थिति',verifiedPlace:'सत्यापित स्थान डेटा',elevation:'ऊँचाई',terrainLanduse:'भू-भाग / भूमि उपयोग',osmCategory:'OSM श्रेणी',quickInfo:'त्वरित जानकारी',officialSite:'आधिकारिक वेबसाइट ↗',sources:'स्रोत',sourcesText:'स्थिति: OpenStreetMap/Nominatim। भू-भाग और सतह: OpenStreetMap/Overpass। ऊँचाई: Copernicus DEM पर Open-Meteo। सारांश: Wikipedia। आधिकारिक वेबसाइट: उपलब्ध होने पर Wikidata P856।',streetNote:'Street View फिलहाल बाहरी सेवा में खुलता है। Perkussus के भीतर इमर्सिव एकीकरण के लिए Google Maps Platform कुंजी या Mapillary टोकन और उनकी उपयोग शर्तों का पालन आवश्यक है।',notClassified:'OSM डेटा में वर्गीकृत नहीं',searching:'खोज जारी है…',noResults:'कोई परिणाम नहीं',locating:'आपका स्थान खोजा जा रहा है…',positionDenied:'स्थान की अनुमति नहीं मिली',map2d:'2D मानचित्र',globe3d:'3D ग्लोब',terrainOn:'3D भू-भाग चालू',terrainOff:'3D भू-भाग बंद',satelliteUnavailable:'उपग्रह उपलब्ध नहीं'
},
pt:{
search:'Pesquisar',layers:'Camadas',language:'Idioma',realEarth:'TERRA REAL',dataLoading:'OPENSTREETMAP · A CARREGAR…',gesture:'Toque num ponto para informação · arraste · faça pinça para ampliar',retry:'TENTAR NOVAMENTE',
liveEyebrow:'TERRA EM DIRETO · DADOS OPERACIONAIS',liveTitle:'O planeta enquanto muda.',liveCopy:'Apenas feeds realmente ligados, com fonte e atualização claramente indicadas.',usgs24:'USGS · 24 H',maxMagnitude:'MAGNITUDE MÁX.',quakesInFeed:'sismos no feed',waitingData:'a aguardar dados',recentEvents:'Eventos recentes',tapEvent:'toque num evento para o localizar',loadingUsgs:'A carregar USGS…',
spaceTitle:'Espaço, sem dados inventados.',spaceCopy:'O módulo Space será ligado a catálogos e missões reais.',spaceStatus:'Estado: interface pronta · integração de dados astronómicos em desenvolvimento.',timeEyebrow:'TEMPO · REALITY REPLAY',timeTitle:'A mesma realidade, ao longo do tempo.',timeCopy:'Arquivos observados, reconstruções científicas e simulações permanecerão separados e claramente identificados.',timeStatus:'Estado: interface pronta · cronologia científica em desenvolvimento.',
navEarth:'TERRA',navLive:'DIRETO',navSpace:'ESPAÇO',navTime:'TEMPO',navMore:'MAIS',askGo:'PERGUNTAR & IR',searchPlace:'Pesquisar um lugar real',searchPlaceholder:'Roma, Everest, Tóquio…',go:'IR',rome:'Roma',italy:'Itália',everest:'Everest',himalaya:'Himalaia',kilauea:'Kīlauea',hawaii:'Havai',tokyo:'Tóquio',japan:'Japão',
realityLayers:'CAMADAS DE REALIDADE',earthViewTitle:'Escolha como ver a Terra',map:'MAPA',satellite:'SATÉLITE',labelsTitle:'Nomes de países, cidades e lugares',labelsSub:'OpenStreetMap / OpenFreeMap',terrain3d:'Terreno 3D',terrainSub:'Modelo digital de elevação Mapterhorn',buildings3d:'Edifícios 3D',buildingsSub:'Quando disponíveis nos dados OpenStreetMap',quakes:'Sismos',quakesSub:'USGS · últimas 24 horas',satelliteNote:'A vista de satélite usa imagens reais, mas não é uma transmissão em direto. O mapa vetorial revela progressivamente estradas, nomes e pontos de interesse à medida que aproxima.',
verifiedReality:'REALIDADE VERIFICADA',information:'Informação',moreModules:'Mais módulos',sourcesTransparency:'Fontes & transparência',provenance:'Proveniência, data e licenças',missions:'Missões',inDevelopment:'Em desenvolvimento',passport:'Passaporte',chooseLanguage:'Escolher idioma',languageNote:'A interface, as fichas informativas e as fontes enciclopédicas seguem o idioma escolhido. Os nomes geográficos usam uma tradução disponível; sem tradução oficial, mantém-se o nome local.',
loadingMapEngine:'A carregar o motor cartográfico…',loadingVector:'A carregar mapa vetorial…',loadingVectorText:'Estradas, cidades, fronteiras e pontos de interesse de OpenStreetMap/OpenFreeMap.',fallbackMap:'A iniciar mapa de reserva…',fallbackText:'O mapa base vetorial não respondeu; serão usados mosaicos raster OpenStreetMap.',addingEarth:'A adicionar o modelo da Terra…',addingEarthText:'Globo 3D, imagens de satélite e modelo de elevação.',connectingLive:'A ligar dados em direto…',earthReady:'Terra pronta.',earthReadyText:'Mapa detalhado, satélite, dados em direto e fichas informativas.',earthFailed:'Não foi possível carregar a Terra.',cartoFailed:'Os serviços cartográficos não responderam.',usgsUnavailable:'O feed USGS está temporariamente indisponível. O mapa continua utilizável.',seismicEvent:'Evento sísmico',depthLower:'profundidade',magnitude:'Magnitude',depth:'Profundidade',coordinates:'Coordenadas',verifiedSource:'Fonte verificada',usgsVerified:'USGS Earthquake Hazards Program · feed GeoJSON oficial das últimas 24 horas.',inspector:'INSPETOR DA REALIDADE',analyzing:'A analisar o ponto…',querying:'A consultar OpenStreetMap, Wikipedia/Wikidata e dados de elevação…',pointEarth:'Ponto na Terra',geoPosition:'Posição geográfica',verifiedPlace:'DADOS DO LOCAL VERIFICADOS',elevation:'Elevação',terrainLanduse:'Terreno / uso do solo',osmCategory:'Categoria OSM',quickInfo:'Informação rápida',officialSite:'Site oficial ↗',sources:'Fontes',sourcesText:'Posição: OpenStreetMap/Nominatim. Terreno e superfície: OpenStreetMap/Overpass. Elevação: Open-Meteo sobre Copernicus DEM. Resumo: Wikipedia. Site oficial: Wikidata P856 quando disponível.',streetNote:'Street View abre, por agora, no serviço externo. A integração imersiva dentro do Perkussus exige uma chave Google Maps Platform ou um token Mapillary, sujeitos às respetivas condições de utilização.',notClassified:'Não classificado nos dados OSM',searching:'A pesquisar…',noResults:'Sem resultados',locating:'A localizar a sua posição…',positionDenied:'Permissão de localização recusada',map2d:'Mapa 2D',globe3d:'Globo 3D',terrainOn:'Terreno 3D ativado',terrainOff:'Terreno 3D desativado',satelliteUnavailable:'Satélite indisponível'
},
zh:{
search:'搜索',layers:'图层',language:'语言',realEarth:'真实地球',dataLoading:'OPENSTREETMAP · 加载中…',gesture:'点击地点查看信息 · 拖动 · 双指缩放',retry:'重试',
liveEyebrow:'实时地球 · 运行数据',liveTitle:'正在变化的地球。',liveCopy:'仅显示真实接入的数据源，并明确标注来源与更新时间。',usgs24:'USGS · 24小时',maxMagnitude:'最大震级',quakesInFeed:'条地震记录',waitingData:'等待数据',recentEvents:'近期事件',tapEvent:'点击事件以定位',loadingUsgs:'正在加载 USGS…',
spaceTitle:'太空，不使用虚构数据。',spaceCopy:'Space 模块将接入真实的目录和航天任务数据。',spaceStatus:'状态：界面已就绪 · 天文数据集成开发中。',timeEyebrow:'时间 · REALITY REPLAY',timeTitle:'同一现实，跨越时间。',timeCopy:'观测档案、科学重建与模拟将始终分开并明确标注。',timeStatus:'状态：界面已就绪 · 科学时间轴开发中。',
navEarth:'地球',navLive:'实时',navSpace:'太空',navTime:'时间',navMore:'更多',askGo:'提问并前往',searchPlace:'搜索真实地点',searchPlaceholder:'罗马、珠穆朗玛峰、东京…',go:'前往',rome:'罗马',italy:'意大利',everest:'珠穆朗玛峰',himalaya:'喜马拉雅山脉',kilauea:'基拉韦厄火山',hawaii:'夏威夷',tokyo:'东京',japan:'日本',
realityLayers:'现实图层',earthViewTitle:'选择地球显示方式',map:'地图',satellite:'卫星',labelsTitle:'国家、城市和地点名称',labelsSub:'OpenStreetMap / OpenFreeMap',terrain3d:'3D 地形',terrainSub:'Mapterhorn 数字高程模型',buildings3d:'3D 建筑',buildingsSub:'在 OpenStreetMap 数据可用时显示',quakes:'地震',quakesSub:'USGS · 最近24小时',satelliteNote:'卫星视图使用真实影像，但并非实时直播。矢量地图会随着缩放逐步显示道路、地名和兴趣点。',
verifiedReality:'已验证现实',information:'信息',moreModules:'更多模块',sourcesTransparency:'来源与透明度',provenance:'数据来源、日期和许可',missions:'任务',inDevelopment:'开发中',passport:'护照',chooseLanguage:'选择语言',languageNote:'界面、信息卡片和百科来源会使用所选语言。地名优先使用可用的正式译名；若没有正式译名，则保留当地名称。',
loadingMapEngine:'正在加载地图引擎…',loadingVector:'正在加载矢量地图…',loadingVectorText:'道路、城市、边界和兴趣点来自 OpenStreetMap/OpenFreeMap。',fallbackMap:'正在启动备用地图…',fallbackText:'矢量底图未响应；改用 OpenStreetMap 栅格瓦片。',addingEarth:'正在添加地球模型…',addingEarthText:'3D 地球、卫星影像和高程模型。',connectingLive:'正在连接实时数据…',earthReady:'地球已就绪。',earthReadyText:'详细地图、卫星影像、实时数据和信息卡片。',earthFailed:'无法加载地球。',cartoFailed:'地图服务未响应。',usgsUnavailable:'USGS 数据源暂时不可用，地图仍可继续使用。',seismicEvent:'地震事件',depthLower:'深度',magnitude:'震级',depth:'深度',coordinates:'坐标',verifiedSource:'已验证来源',usgsVerified:'USGS Earthquake Hazards Program · 最近24小时官方 GeoJSON 数据源。',inspector:'现实检查器',analyzing:'正在分析地点…',querying:'正在查询 OpenStreetMap、Wikipedia/Wikidata 和高程数据…',pointEarth:'地球上的地点',geoPosition:'地理位置',verifiedPlace:'已验证地点数据',elevation:'海拔',terrainLanduse:'地形 / 土地利用',osmCategory:'OSM 类别',quickInfo:'快速信息',officialSite:'官方网站 ↗',sources:'来源',sourcesText:'位置：OpenStreetMap/Nominatim。地形与地表：OpenStreetMap/Overpass。高程：基于 Copernicus DEM 的 Open-Meteo。摘要：Wikipedia。官方网站：可用时使用 Wikidata P856。',streetNote:'Street View 目前会在外部服务中打开。若要在 Perkussus 内实现沉浸式集成，需要 Google Maps Platform 密钥或 Mapillary 令牌，并遵守其使用条款。',notClassified:'OSM 数据中未分类',searching:'正在搜索…',noResults:'没有结果',locating:'正在获取你的位置…',positionDenied:'未获得位置权限',map2d:'2D 地图',globe3d:'3D 地球',terrainOn:'3D 地形已开启',terrainOff:'3D 地形已关闭',satelliteUnavailable:'卫星图不可用'
},
ja:{
search:'検索',layers:'レイヤー',language:'言語',realEarth:'リアル・アース',dataLoading:'OPENSTREETMAP · 読み込み中…',gesture:'地点をタップして情報表示 · ドラッグ · ピンチでズーム',retry:'再試行',
liveEyebrow:'LIVE EARTH · 運用データ',liveTitle:'変化し続ける地球。',liveCopy:'実際に接続されたデータフィードのみを表示し、出典と更新状況を明示します。',usgs24:'USGS · 24時間',maxMagnitude:'最大マグニチュード',quakesInFeed:'件の地震',waitingData:'データ待機中',recentEvents:'最近のイベント',tapEvent:'イベントをタップして位置を表示',loadingUsgs:'USGS を読み込み中…',
spaceTitle:'架空のデータを使わない宇宙。',spaceCopy:'Space モジュールは実在するカタログやミッションデータに接続されます。',spaceStatus:'状態：インターフェース準備完了 · 天文データ統合を開発中。',timeEyebrow:'TIME · REALITY REPLAY',timeTitle:'同じ現実を、時間を越えて。',timeCopy:'観測記録、科学的復元、シミュレーションは分離し、明確に表示します。',timeStatus:'状態：インターフェース準備完了 · 科学タイムラインを開発中。',
navEarth:'地球',navLive:'ライブ',navSpace:'宇宙',navTime:'時間',navMore:'その他',askGo:'質問して移動',searchPlace:'実在する場所を検索',searchPlaceholder:'ローマ、エベレスト、東京…',go:'移動',rome:'ローマ',italy:'イタリア',everest:'エベレスト',himalaya:'ヒマラヤ',kilauea:'キラウエア',hawaii:'ハワイ',tokyo:'東京',japan:'日本',
realityLayers:'リアリティ・レイヤー',earthViewTitle:'地球の表示方法を選択',map:'地図',satellite:'衛星',labelsTitle:'国・都市・場所の名称',labelsSub:'OpenStreetMap / OpenFreeMap',terrain3d:'3D 地形',terrainSub:'Mapterhorn デジタル標高モデル',buildings3d:'3D 建物',buildingsSub:'OpenStreetMap データに存在する場合',quakes:'地震',quakesSub:'USGS · 過去24時間',satelliteNote:'衛星表示には実際の画像を使用しますが、ライブ映像ではありません。ベクターマップはズームに応じて道路、地名、POIを段階的に表示します。',
verifiedReality:'検証済みリアリティ',information:'情報',moreModules:'その他のモジュール',sourcesTransparency:'出典と透明性',provenance:'由来・日付・ライセンス',missions:'ミッション',inDevelopment:'開発中',passport:'パスポート',chooseLanguage:'言語を選択',languageNote:'インターフェース、情報カード、百科事典の出典は選択した言語に合わせます。地名は利用可能な正式訳を優先し、正式訳がない場合は現地名を保持します。',
loadingMapEngine:'地図エンジンを読み込み中…',loadingVector:'ベクターマップを読み込み中…',loadingVectorText:'OpenStreetMap/OpenFreeMap の道路、都市、境界、POIを読み込んでいます。',fallbackMap:'予備地図を起動中…',fallbackText:'ベクター背景地図が応答しないため、OpenStreetMap のラスタータイルを使用します。',addingEarth:'地球モデルを追加中…',addingEarthText:'3D 地球、衛星画像、標高モデル。',connectingLive:'ライブデータに接続中…',earthReady:'地球の準備完了。',earthReadyText:'詳細地図、衛星画像、ライブデータ、情報カードを利用できます。',earthFailed:'地球を読み込めませんでした。',cartoFailed:'地図サービスが応答しませんでした。',usgsUnavailable:'USGS フィードは一時的に利用できません。地図は引き続き使用できます。',seismicEvent:'地震イベント',depthLower:'深さ',magnitude:'マグニチュード',depth:'深さ',coordinates:'座標',verifiedSource:'検証済みの出典',usgsVerified:'USGS Earthquake Hazards Program · 過去24時間の公式 GeoJSON フィード。',inspector:'リアリティ・インスペクター',analyzing:'地点を分析中…',querying:'OpenStreetMap、Wikipedia/Wikidata、標高データを照会中…',pointEarth:'地球上の地点',geoPosition:'地理的位置',verifiedPlace:'検証済み地点データ',elevation:'標高',terrainLanduse:'地形 / 土地利用',osmCategory:'OSM カテゴリ',quickInfo:'クイック情報',officialSite:'公式サイト ↗',sources:'出典',sourcesText:'位置：OpenStreetMap/Nominatim。地形・地表：OpenStreetMap/Overpass。標高：Copernicus DEM を用いた Open-Meteo。概要：Wikipedia。公式サイト：利用可能な場合は Wikidata P856。',streetNote:'Street View は現在、外部サービスで開きます。Perkussus 内に没入型で統合するには、Google Maps Platform のキーまたは Mapillary トークンが必要で、それぞれの利用規約が適用されます。',notClassified:'OSM データでは未分類',searching:'検索中…',noResults:'結果がありません',locating:'現在地を取得中…',positionDenied:'位置情報の許可がありません',map2d:'2D 地図',globe3d:'3D 地球',terrainOn:'3D 地形オン',terrainOff:'3D 地形オフ',satelliteUnavailable:'衛星表示を利用できません'
}
};
const TERRAIN={
'Acqua':{en:'Water',fr:'Eau',es:'Agua',de:'Wasser',ru:'Вода',hi:'पानी',pt:'Água',zh:'水域',ja:'水域'},
'Bosco':{en:'Woodland',fr:'Bois',es:'Bosque',de:'Wald',ru:'Лес',hi:'वन क्षेत्र',pt:'Bosque',zh:'林地',ja:'森林'},
'Prateria':{en:'Grassland',fr:'Prairie',es:'Pradera',de:'Grasland',ru:'Луг/степь',hi:'घासभूमि',pt:'Pradaria',zh:'草地',ja:'草原'},
'Roccia affiorante':{en:'Bare rock',fr:'Roche affleurante',es:'Roca expuesta',de:'Freiliegender Fels',ru:'Открытая скала',hi:'उजागर चट्टान',pt:'Rocha exposta',zh:'裸岩',ja:'露岩'},
'Ghiaione':{en:'Scree',fr:'Éboulis',es:'Pedrera',de:'Geröllfeld',ru:'Осыпь',hi:'पत्थरीला ढाल',pt:'Cascalheira',zh:'碎石坡',ja:'ガレ場'},
'Ghiaia':{en:'Gravel',fr:'Gravier',es:'Grava',de:'Kies',ru:'Гравий',hi:'बजरी',pt:'Cascalho',zh:'砾石',ja:'砂利'},
'Sabbia':{en:'Sand',fr:'Sable',es:'Arena',de:'Sand',ru:'Песок',hi:'रेत',pt:'Areia',zh:'沙地',ja:'砂地'},
'Spiaggia':{en:'Beach',fr:'Plage',es:'Playa',de:'Strand',ru:'Пляж',hi:'समुद्र तट',pt:'Praia',zh:'海滩',ja:'海岸'},
'Zona umida':{en:'Wetland',fr:'Zone humide',es:'Humedal',de:'Feuchtgebiet',ru:'Водно-болотная зона',hi:'आर्द्रभूमि',pt:'Zona húmida',zh:'湿地',ja:'湿地'},
'Macchia/arbusti':{en:'Scrub',fr:'Broussailles',es:'Matorral',de:'Buschland',ru:'Кустарник',hi:'झाड़ी क्षेत्र',pt:'Matagal',zh:'灌木地',ja:'低木地'},
'Brughiera':{en:'Heath',fr:'Lande',es:'Brezal',de:'Heide',ru:'Вересковая пустошь',hi:'हीथ भूमि',pt:'Charneca',zh:'荒原',ja:'ヒース地'},
'Ghiacciaio':{en:'Glacier',fr:'Glacier',es:'Glaciar',de:'Gletscher',ru:'Ледник',hi:'हिमनद',pt:'Glaciar',zh:'冰川',ja:'氷河'},
'Vetta/montagna':{en:'Peak / mountain',fr:'Sommet / montagne',es:'Pico / montaña',de:'Gipfel / Berg',ru:'Вершина / гора',hi:'शिखर / पर्वत',pt:'Pico / montanha',zh:'山峰 / 山地',ja:'山頂 / 山地'},
'Area vulcanica':{en:'Volcanic area',fr:'Zone volcanique',es:'Zona volcánica',de:'Vulkangebiet',ru:'Вулканическая зона',hi:'ज्वालामुखीय क्षेत्र',pt:'Área vulcânica',zh:'火山区',ja:'火山地域'},
'Falesia':{en:'Cliff',fr:'Falaise',es:'Acantilado',de:'Klippe',ru:'Утёс',hi:'खड़ी चट्टान',pt:'Falésia',zh:'悬崖',ja:'崖'},
'Foresta':{en:'Forest',fr:'Forêt',es:'Bosque',de:'Forst',ru:'Лес',hi:'जंगल',pt:'Floresta',zh:'森林',ja:'森林'},
'Terreno agricolo':{en:'Farmland',fr:'Terres agricoles',es:'Tierra agrícola',de:'Ackerland',ru:'Сельхозугодья',hi:'कृषि भूमि',pt:'Terreno agrícola',zh:'农田',ja:'農地'},
'Area agricola':{en:'Farmyard',fr:'Zone agricole',es:'Zona agrícola',de:'Hofbereich',ru:'Сельскохозяйственная зона',hi:'कृषि क्षेत्र',pt:'Área agrícola',zh:'农业区',ja:'農業地域'},
'Prato':{en:'Meadow',fr:'Prairie',es:'Prado',de:'Wiese',ru:'Луг',hi:'घास का मैदान',pt:'Prado',zh:'草甸',ja:'牧草地'},
'Frutteto':{en:'Orchard',fr:'Verger',es:'Huerto frutal',de:'Obstgarten',ru:'Фруктовый сад',hi:'फलोद्यान',pt:'Pomar',zh:'果园',ja:'果樹園'},
'Vigneto':{en:'Vineyard',fr:'Vignoble',es:'Viñedo',de:'Weinberg',ru:'Виноградник',hi:'अंगूर का बाग',pt:'Vinha',zh:'葡萄园',ja:'ブドウ畑'},
'Area urbana residenziale':{en:'Residential urban area',fr:'Zone urbaine résidentielle',es:'Zona urbana residencial',de:'Wohngebiet',ru:'Жилая городская зона',hi:'आवासीय शहरी क्षेत्र',pt:'Área urbana residencial',zh:'城市住宅区',ja:'住宅地'},
'Area commerciale':{en:'Commercial area',fr:'Zone commerciale',es:'Zona comercial',de:'Gewerbegebiet',ru:'Коммерческая зона',hi:'वाणिज्यिक क्षेत्र',pt:'Área comercial',zh:'商业区',ja:'商業地域'},
'Area industriale':{en:'Industrial area',fr:'Zone industrielle',es:'Zona industrial',de:'Industriegebiet',ru:'Промышленная зона',hi:'औद्योगिक क्षेत्र',pt:'Área industrial',zh:'工业区',ja:'工業地域'},
'Cava':{en:'Quarry',fr:'Carrière',es:'Cantera',de:'Steinbruch',ru:'Карьер',hi:'खदान',pt:'Pedreira',zh:'采石场',ja:'採石場'},
'Area ricreativa':{en:'Recreation area',fr:'Zone de loisirs',es:'Área recreativa',de:'Freizeitfläche',ru:'Рекреационная зона',hi:'मनोरंजन क्षेत्र',pt:'Área recreativa',zh:'休闲区',ja:'レクリエーション区域'},
'Prato/erba':{en:'Grass',fr:'Herbe',es:'Hierba',de:'Gras',ru:'Трава',hi:'घास',pt:'Relva',zh:'草地',ja:'草地'},
'Asfalto':{en:'Asphalt',fr:'Asphalte',es:'Asfalto',de:'Asphalt',ru:'Асфальт',hi:'डामर',pt:'Asfalto',zh:'沥青',ja:'アスファルト'},
'Superficie pavimentata':{en:'Paved surface',fr:'Surface revêtue',es:'Superficie pavimentada',de:'Befestigte Oberfläche',ru:'Мощёная поверхность',hi:'पक्की सतह',pt:'Superfície pavimentada',zh:'铺装路面',ja:'舗装面'},
'Calcestruzzo':{en:'Concrete',fr:'Béton',es:'Hormigón',de:'Beton',ru:'Бетон',hi:'कंक्रीट',pt:'Betão',zh:'混凝土',ja:'コンクリート'},
'Terreno naturale':{en:'Natural ground',fr:'Sol naturel',es:'Terreno natural',de:'Naturboden',ru:'Естественный грунт',hi:'प्राकृतिक भूमि',pt:'Terreno natural',zh:'自然地面',ja:'自然地面'},
'Terra':{en:'Dirt / earth',fr:'Terre',es:'Tierra',de:'Erde',ru:'Грунт',hi:'मिट्टी',pt:'Terra',zh:'土壤',ja:'土'},
'Erba':{en:'Grass',fr:'Herbe',es:'Hierba',de:'Gras',ru:'Трава',hi:'घास',pt:'Relva',zh:'草地',ja:'草'},
'Roccia':{en:'Rock',fr:'Roche',es:'Roca',de:'Fels',ru:'Скала',hi:'चट्टान',pt:'Rocha',zh:'岩石',ja:'岩石'},
'Superficie non pavimentata':{en:'Unpaved surface',fr:'Surface non revêtue',es:'Superficie sin pavimentar',de:'Unbefestigte Oberfläche',ru:'Немощёная поверхность',hi:'कच्ची सतह',pt:'Superfície não pavimentada',zh:'未铺装路面',ja:'未舗装面'}
};
function savedLang(){try{const x=localStorage.getItem('pv_language');if(LANGS[x])return x}catch{}const n=(navigator.language||'it').toLowerCase();const k=n.split('-')[0];return LANGS[k]?k:'it'}
let current=savedLang();
const t=k=>(D[current]&&D[current][k])||D.en[k]||D.it[k]||k;
const meta=()=>LANGS[current]||LANGS.it;
const originalFetch=window.fetch.bind(window);
window.fetch=function(input,init){
  try{
    const raw=typeof input==='string'?input:input?.url;
    if(raw){let u=new URL(raw,location.href);
      if(u.hostname==='nominatim.openstreetmap.org'){u.searchParams.set('accept-language',meta().api);input=u.href}
      if(/(^|\.)wikipedia\.org$/.test(u.hostname)){u.hostname=`${meta().wiki}.wikipedia.org`;input=u.href}
    }
  }catch{}
  return originalFetch(input,init)
};
const dateLocale=meta().locale;
const _date=Date.prototype.toLocaleString;Date.prototype.toLocaleString=function(locales,options){if(locales==='it-IT')locales=(LANGS[current]||LANGS.it).locale;return _date.call(this,locales,options)};
const _num=Number.prototype.toLocaleString;Number.prototype.toLocaleString=function(locales,options){if(locales==='it-IT')locales=(LANGS[current]||LANGS.it).locale;return _num.call(this,locales,options)};
function applyStatic(){
  document.documentElement.lang=current==='zh'?'zh-CN':current;
  document.querySelectorAll('[data-i18n]').forEach(el=>{const v=t(el.dataset.i18n);if(v!==undefined)el.textContent=v});
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.setAttribute('placeholder',t(el.dataset.i18nPlaceholder)));
  document.querySelectorAll('[data-i18n-aria]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAria)));
  const b=document.querySelector('#languageOpen');if(b)b.textContent=current.toUpperCase();
  document.querySelectorAll('[data-language]').forEach(el=>el.classList.toggle('active',el.dataset.language===current));
}
const exact={
'Caricamento motore cartografico…':'loadingMapEngine','Caricamento mappa vettoriale…':'loadingVector','Strade, città, confini e punti d’interesse da OpenStreetMap/OpenFreeMap.':'loadingVectorText','Attivo la mappa di riserva…':'fallbackMap','Il basemap vettoriale non ha risposto: uso OpenStreetMap raster.':'fallbackText','Aggiungo il modello della Terra…':'addingEarth','Globo 3D, satellite e modello di elevazione.':'addingEarthText','Collegamento dati live…':'connectingLive','Terra pronta.':'earthReady','Mappa dettagliata, satellite, dati live e schede informative.':'earthReadyText','La Terra non si è caricata.':'earthFailed','I servizi cartografici non hanno risposto.':'cartoFailed','Feed USGS temporaneamente non raggiungibile. La mappa resta utilizzabile.':'usgsUnavailable','Evento sismico':'seismicEvent','Magnitudo':'magnitude','Profondità':'depth','Coordinate':'coordinates','Fonte verificata':'verifiedSource','USGS Earthquake Hazards Program · feed GeoJSON ufficiale delle ultime 24 ore.':'usgsVerified','REALITY INSPECTOR':'inspector','Analisi del punto…':'analyzing','Interrogo OpenStreetMap, Wikipedia/Wikidata e dati di elevazione…':'querying','Punto sulla Terra':'pointEarth','Posizione geografica':'geoPosition','VERIFIED PLACE DATA':'verifiedPlace','Elevazione':'elevation','Terreno / uso suolo':'terrainLanduse','Categoria OSM':'osmCategory','Informazioni rapide':'quickInfo','Sito ufficiale ↗':'officialSite','Fonti':'sources','Posizione: OpenStreetMap/Nominatim. Terreno e superficie: OpenStreetMap/Overpass. Elevazione: Open-Meteo su Copernicus DEM. Sintesi: Wikipedia. Sito ufficiale: Wikidata P856 quando disponibile.':'sourcesText',"Street View si apre per ora nel servizio esterno. L'integrazione immersiva dentro Perkussus richiede una chiave Google Maps Platform o un token Mapillary con le relative condizioni d'uso.":'streetNote','Non classificato nei dati OSM':'notClassified','Ricerca…':'searching','Nessun risultato':'noResults','Cerco la posizione…':'locating','Posizione non autorizzata':'positionDenied','Mappa 2D':'map2d','Globo 3D':'globe3d','Terreno 3D attivo':'terrainOn','Terreno 3D disattivato':'terrainOff','Satellite non disponibile':'satelliteUnavailable'
};
function localizeTerrain(s){const x=TERRAIN[s];return x?(current==='it'?s:(x[current]||x.en||s)):s}
function translateTextNode(n){let s=n.nodeValue;if(!s||!s.trim())return;const trim=s.trim();if(exact[trim]){n.nodeValue=s.replace(trim,t(exact[trim]));return}const terrain=localizeTerrain(trim);if(terrain!==trim){n.nodeValue=s.replace(trim,terrain);return}if(current!=='it'){
  s=s.replace(/· profondità (\d+) km/g,`· ${t('depthLower')} $1 km`).replace(/^Coordinate:/,`${t('coordinates')}:`).replace(/^Geologia:/,current==='en'?'Geology:':current==='fr'?'Géologie:':current==='es'?'Geología:':current==='de'?'Geologie:':current==='ru'?'Геология:':current==='hi'?'भूविज्ञान:':current==='pt'?'Geologia:':current==='zh'?'地质:':'地質:');n.nodeValue=s
}}
function translateDynamic(root=document){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const arr=[];while(w.nextNode())arr.push(w.currentNode);arr.forEach(translateTextNode)}
let obs;
function startObserver(){if(obs)return;obs=new MutationObserver(ms=>{for(const m of ms){m.addedNodes.forEach(n=>{if(n.nodeType===1||n.nodeType===3)translateDynamic(n)});if(m.type==='characterData')translateTextNode(m.target)}});obs.observe(document.body,{subtree:true,childList:true,characterData:true})}
function closeLanguage(){const sh=document.querySelector('#languageSheet');if(sh)sh.classList.remove('open');const sc=document.querySelector('#scrim');if(sc&&!document.querySelector('.sheet.open'))sc.classList.remove('open')}
function openLanguage(){document.querySelectorAll('.sheet.open').forEach(x=>x.classList.remove('open'));const sh=document.querySelector('#languageSheet');if(sh){sh.classList.add('open');sh.setAttribute('aria-hidden','false')}document.querySelector('#scrim')?.classList.add('open')}
function bind(){
  document.querySelector('#languageOpen')?.addEventListener('click',openLanguage);
  document.querySelector('#languageSheet [data-lang-close]')?.addEventListener('click',closeLanguage);
  document.querySelector('#scrim')?.addEventListener('click',closeLanguage);
  ['#searchOpen','#layersOpen','#moreOpen','#earthInfoOpen'].forEach(s=>document.querySelector(s)?.addEventListener('click',closeLanguage,true));
  document.querySelectorAll('[data-language]').forEach(b=>b.addEventListener('click',()=>{const code=b.dataset.language;if(!LANGS[code]||code===current)return;try{localStorage.setItem('pv_language',code)}catch{}current=code;applyStatic();setTimeout(()=>location.reload(),80)}));
}
window.PV_I18N={get language(){return current},t,languages:LANGS,locale:()=>meta().locale,apiLanguage:()=>meta().api};
function init(){applyStatic();translateDynamic(document.body);bind();startObserver()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();