const lang=()=>{try{return localStorage.getItem('pv_language')||'it'}catch{return'it'}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s||'').trim().toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const text={
 it:{placeholder:'Cerca luoghi, ristoranti, hotel, vie…',near:'Vicino a te sulla mappa',loading:'Ricerca in corso…',none:'Nessun risultato in questa zona',results:'risultati',details:'DETTAGLI DEL LUOGO',website:'Sito web',phone:'Telefono',hours:'Orari',address:'Indirizzo',cuisine:'Cucina',brand:'Marchio',source:'Fonte',osm:'OpenStreetMap',zoom:'Avvicinati a una città per cercare nelle vicinanze'},
 en:{placeholder:'Search places, restaurants, hotels, streets…',near:'Nearby on the map',loading:'Searching…',none:'No results in this area',results:'results',details:'PLACE DETAILS',website:'Website',phone:'Phone',hours:'Opening hours',address:'Address',cuisine:'Cuisine',brand:'Brand',source:'Source',osm:'OpenStreetMap',zoom:'Zoom into a city to search nearby'},
 fr:{placeholder:'Rechercher lieux, restaurants, hôtels, rues…',near:'À proximité sur la carte',loading:'Recherche…',none:'Aucun résultat dans cette zone',results:'résultats',details:'DÉTAILS DU LIEU',website:'Site web',phone:'Téléphone',hours:'Horaires',address:'Adresse',cuisine:'Cuisine',brand:'Marque',source:'Source',osm:'OpenStreetMap',zoom:'Zoomez sur une ville pour chercher à proximité'},
 es:{placeholder:'Buscar lugares, restaurantes, hoteles, calles…',near:'Cerca en el mapa',loading:'Buscando…',none:'No hay resultados en esta zona',results:'resultados',details:'DETALLES DEL LUGAR',website:'Sitio web',phone:'Teléfono',hours:'Horario',address:'Dirección',cuisine:'Cocina',brand:'Marca',source:'Fuente',osm:'OpenStreetMap',zoom:'Acércate a una ciudad para buscar cerca'},
 de:{placeholder:'Orte, Restaurants, Hotels, Straßen suchen…',near:'In der Nähe auf der Karte',loading:'Suche…',none:'Keine Ergebnisse in diesem Gebiet',results:'Ergebnisse',details:'ORTSDETAILS',website:'Website',phone:'Telefon',hours:'Öffnungszeiten',address:'Adresse',cuisine:'Küche',brand:'Marke',source:'Quelle',osm:'OpenStreetMap',zoom:'Zoome in eine Stadt, um in der Nähe zu suchen'},
 ru:{placeholder:'Места, рестораны, отели, улицы…',near:'Рядом на карте',loading:'Поиск…',none:'В этой зоне ничего не найдено',results:'результатов',details:'СВЕДЕНИЯ О МЕСТЕ',website:'Сайт',phone:'Телефон',hours:'Часы работы',address:'Адрес',cuisine:'Кухня',brand:'Бренд',source:'Источник',osm:'OpenStreetMap',zoom:'Приблизьте город для поиска рядом'},
 hi:{placeholder:'स्थान, रेस्तराँ, होटल, सड़कें खोजें…',near:'मानचित्र पर आस-पास',loading:'खोज जारी है…',none:'इस क्षेत्र में परिणाम नहीं मिले',results:'परिणाम',details:'स्थान का विवरण',website:'वेबसाइट',phone:'फ़ोन',hours:'समय',address:'पता',cuisine:'भोजन',brand:'ब्रांड',source:'स्रोत',osm:'OpenStreetMap',zoom:'आस-पास खोजने के लिए शहर पर ज़ूम करें'},
 pt:{placeholder:'Pesquisar locais, restaurantes, hotéis, ruas…',near:'Perto no mapa',loading:'A pesquisar…',none:'Nenhum resultado nesta zona',results:'resultados',details:'DETALHES DO LOCAL',website:'Site',phone:'Telefone',hours:'Horário',address:'Endereço',cuisine:'Cozinha',brand:'Marca',source:'Fonte',osm:'OpenStreetMap',zoom:'Aproxime uma cidade para pesquisar perto'},
 zh:{placeholder:'搜索地点、餐厅、酒店、街道…',near:'地图附近',loading:'正在搜索…',none:'该区域没有结果',results:'个结果',details:'地点详情',website:'网站',phone:'电话',hours:'营业时间',address:'地址',cuisine:'菜系',brand:'品牌',source:'来源',osm:'OpenStreetMap',zoom:'请放大到城市后搜索附近'},
 ja:{placeholder:'場所、レストラン、ホテル、道路を検索…',near:'地図周辺',loading:'検索中…',none:'この地域では見つかりません',results:'件',details:'場所の詳細',website:'ウェブサイト',phone:'電話',hours:'営業時間',address:'住所',cuisine:'料理',brand:'ブランド',source:'出典',osm:'OpenStreetMap',zoom:'都市まで拡大して周辺検索してください'}
};
const tr=()=>text[lang()]||text.en;
const cats=[
 {id:'restaurant',icon:'🍴',l:{it:'Ristoranti',en:'Restaurants',fr:'Restaurants',es:'Restaurantes',de:'Restaurants',ru:'Рестораны',hi:'रेस्तराँ',pt:'Restaurantes',zh:'餐厅',ja:'レストラン'},q:'nwr["amenity"="restaurant"]',a:['ristorante','ristoranti','restaurant','restaurants']},
 {id:'cafe',icon:'☕',l:{it:'Caffè',en:'Cafés',fr:'Cafés',es:'Cafés',de:'Cafés',ru:'Кафе',hi:'कैफ़े',pt:'Cafés',zh:'咖啡馆',ja:'カフェ'},q:'nwr["amenity"~"cafe|bar|pub"]',a:['caffe','caffè','cafe','bar','pub']},
 {id:'hotel',icon:'▣',l:{it:'Hotel',en:'Hotels',fr:'Hôtels',es:'Hoteles',de:'Hotels',ru:'Отели',hi:'होटल',pt:'Hotéis',zh:'酒店',ja:'ホテル'},q:'nwr["tourism"~"hotel|guest_house|hostel|motel"]',a:['hotel','hotels','albergo','alberghi']},
 {id:'parking',icon:'P',l:{it:'Parcheggi',en:'Parking',fr:'Parkings',es:'Aparcamientos',de:'Parkplätze',ru:'Парковки',hi:'पार्किंग',pt:'Estacionamentos',zh:'停车场',ja:'駐車場'},q:'nwr["amenity"="parking"]',a:['parcheggio','parcheggi','parking']},
 {id:'pharmacy',icon:'✚',l:{it:'Farmacie',en:'Pharmacies',fr:'Pharmacies',es:'Farmacias',de:'Apotheken',ru:'Аптеки',hi:'फ़ार्मेसी',pt:'Farmácias',zh:'药店',ja:'薬局'},q:'nwr["amenity"="pharmacy"]',a:['farmacia','farmacie','pharmacy','pharmacies']},
 {id:'supermarket',icon:'□',l:{it:'Supermercati',en:'Supermarkets',fr:'Supermarchés',es:'Supermercados',de:'Supermärkte',ru:'Супермаркеты',hi:'सुपरमार्केट',pt:'Supermercados',zh:'超市',ja:'スーパー'},q:'nwr["shop"="supermarket"]',a:['supermercato','supermercati','supermarket']},
 {id:'hospital',icon:'H',l:{it:'Ospedali',en:'Hospitals',fr:'Hôpitaux',es:'Hospitales',de:'Krankenhäuser',ru:'Больницы',hi:'अस्पताल',pt:'Hospitais',zh:'医院',ja:'病院'},q:'nwr["amenity"~"hospital|clinic"]',a:['ospedale','ospedali','clinica','cliniche','hospital']},
 {id:'fuel',icon:'⛽',l:{it:'Carburante',en:'Fuel',fr:'Stations-service',es:'Gasolineras',de:'Tankstellen',ru:'Заправки',hi:'ईंधन',pt:'Postos',zh:'加油站',ja:'ガソリンスタンド'},q:'nwr["amenity"="fuel"]',a:['benzina','distributore','distributori','carburante','fuel']},
 {id:'museum',icon:'◇',l:{it:'Musei',en:'Museums',fr:'Musées',es:'Museos',de:'Museen',ru:'Музеи',hi:'संग्रहालय',pt:'Museus',zh:'博物馆',ja:'博物館'},q:'nwr["tourism"="museum"]',a:['museo','musei','museum']},
 {id:'attraction',icon:'◎',l:{it:'Attrazioni',en:'Attractions',fr:'Attractions',es:'Atracciones',de:'Sehenswürdigkeiten',ru:'Достопримечательности',hi:'आकर्षण',pt:'Atrações',zh:'景点',ja:'観光スポット'},q:'nwr["tourism"~"attraction|viewpoint|zoo|theme_park"]',a:['attrazione','attrazioni','attraction']},
 {id:'station',icon:'⇆',l:{it:'Stazioni',en:'Stations',fr:'Gares',es:'Estaciones',de:'Bahnhöfe',ru:'Станции',hi:'स्टेशन',pt:'Estações',zh:'车站',ja:'駅'},q:'nwr["railway"="station"]',a:['stazione','stazioni','station']},
 {id:'airport',icon:'✈',l:{it:'Aeroporti',en:'Airports',fr:'Aéroports',es:'Aeropuertos',de:'Flughäfen',ru:'Аэропорты',hi:'हवाई अड्डे',pt:'Aeroportos',zh:'机场',ja:'空港'},q:'nwr["aeroway"="aerodrome"]',a:['aeroporto','aeroporti','airport']},
 {id:'atm',icon:'€',l:{it:'Bancomat',en:'ATMs',fr:'Distributeurs',es:'Cajeros',de:'Geldautomaten',ru:'Банкоматы',hi:'एटीएम',pt:'Caixas',zh:'ATM',ja:'ATM'},q:'nwr["amenity"="atm"]',a:['bancomat','atm']}
];
const catLabel=c=>c.l[lang()]||c.l.en;
let map,searchTimer,searchAbort,activeCat=null,resultById=new Map(),boundPoiLayers=new Set();

function addCss(){if(document.querySelector('link[data-pv-explore]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='./map-explore.css?v=1';l.dataset.pvExplore='1';document.head.appendChild(l)}
function createUi(){
 const view=document.querySelector('#earthView');if(!view||document.querySelector('#pvExploreShell'))return;
 const shell=document.createElement('div');shell.id='pvExploreShell';shell.className='pv-explore-shell';shell.innerHTML=`<form class="pv-explore-search" id="pvExploreForm"><span class="pv-search-icon">⌕</span><input id="pvExploreInput" autocomplete="off" spellcheck="false"><button type="button" id="pvExploreClear" class="hidden">×</button></form><div class="pv-explore-dropdown" id="pvExploreDropdown" hidden></div>`;view.appendChild(shell);
 const strip=document.createElement('div');strip.id='pvCategoryStrip';strip.className='pv-category-strip hidden';view.appendChild(strip);
 const status=document.createElement('div');status.id='pvMapSearchStatus';status.className='pv-map-search-status';view.appendChild(status);
 renderLanguage();
 document.querySelector('#pvExploreInput').addEventListener('input',onInput);
 document.querySelector('#pvExploreInput').addEventListener('focus',()=>{if(document.querySelector('#pvExploreInput').value.trim().length>=2)onInput()});
 document.querySelector('#pvExploreForm').addEventListener('submit',e=>{e.preventDefault();submitSearch(document.querySelector('#pvExploreInput').value)});
 document.querySelector('#pvExploreClear').addEventListener('click',()=>{const i=document.querySelector('#pvExploreInput');i.value='';document.querySelector('#pvExploreDropdown').hidden=true;document.querySelector('#pvExploreClear').classList.add('hidden');clearCategoryResults()});
 document.addEventListener('click',e=>{if(!e.target.closest('#pvExploreShell'))document.querySelector('#pvExploreDropdown').hidden=true;if(e.target.closest('[data-language]'))setTimeout(renderLanguage,80)});
}
function renderLanguage(){
 const i=document.querySelector('#pvExploreInput');if(i)i.placeholder=tr().placeholder;
 const s=document.querySelector('#pvCategoryStrip');if(s)s.innerHTML=cats.map(c=>`<button class="pv-category-chip${activeCat===c.id?' active':''}" data-pv-cat="${c.id}"><span>${c.icon}</span>${esc(catLabel(c))}</button>`).join('');
 document.querySelectorAll('[data-pv-cat]').forEach(b=>b.addEventListener('click',()=>searchCategory(cats.find(c=>c.id===b.dataset.pvCat))));
}
function setStatus(msg,error=false,linger=2600){const e=document.querySelector('#pvMapSearchStatus');if(!e)return;e.textContent=msg;e.classList.toggle('error',error);e.classList.add('show');clearTimeout(setStatus.t);if(linger)setStatus.t=setTimeout(()=>e.classList.remove('show'),linger)}
function updateStrip(){const s=document.querySelector('#pvCategoryStrip');if(!s||!map)return;s.classList.toggle('hidden',(map.getZoom?.()||0)<8.5)}

async function photon(q,limit=8){
 searchAbort?.abort();searchAbort=new AbortController();const u=new URL('https://photon.komoot.io/api/');u.searchParams.set('q',q);u.searchParams.set('limit',String(limit));const l=lang();if(['en','de','fr'].includes(l))u.searchParams.set('lang',l);const c=map?.getCenter?.();if(c){u.searchParams.set('lat',c.lat);u.searchParams.set('lon',c.lng)}
 let r=await fetch(u,{signal:searchAbort.signal});if(!r.ok){u.searchParams.delete('lang');r=await fetch(u,{signal:searchAbort.signal})}if(!r.ok)throw new Error('search');return (await r.json()).features||[];
}
function photonTitle(f){const p=f.properties||{};return p.name||p.street||p.city||p.state||p.country||'—'}
function photonSub(f){const p=f.properties||{};return [p.street,p.city,p.state,p.country].filter((v,i,a)=>v&&v!==photonTitle(f)&&a.indexOf(v)===i).join(' · ')}
function onInput(){const i=document.querySelector('#pvExploreInput'),d=document.querySelector('#pvExploreDropdown'),c=document.querySelector('#pvExploreClear');const q=i.value.trim();c.classList.toggle('hidden',!q);clearTimeout(searchTimer);if(q.length<2){d.hidden=true;return}searchTimer=setTimeout(async()=>{try{const rows=await photon(q);const category=findCategoryPrefix(q);d.innerHTML=`${category?`<button class="pv-explore-suggestion" data-category="${category.cat.id}" data-category-place="${esc(category.place)}"><span class="pin">${category.cat.icon}</span><span class="copy"><b>${esc(catLabel(category.cat))}</b><small>${esc(category.place||tr().near)}</small></span></button>`:''}${rows.map((f,n)=>`<button class="pv-explore-suggestion" data-photon="${n}"><span class="pin">⌖</span><span class="copy"><b>${esc(photonTitle(f))}</b><small>${esc(photonSub(f))}</small></span></button>`).join('')}`;d.hidden=false;d._rows=rows;d.querySelectorAll('[data-photon]').forEach(b=>b.addEventListener('click',()=>openPhoton(rows[Number(b.dataset.photon)])));d.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>runCategoryIntent(cats.find(c=>c.id===b.dataset.category),b.dataset.categoryPlace)))}catch(e){if(e.name!=='AbortError')d.hidden=true}},230)}
function findCategoryPrefix(q){const n=norm(q);for(const c of cats){const all=[catLabel(c),...c.a].map(norm).sort((a,b)=>b.length-a.length);for(const a of all){if(n===a)return{cat:c,place:''};if(n.startsWith(a+' '))return{cat:c,place:q.slice(a.length).trim()}}}return null}
async function submitSearch(q){q=q.trim();if(!q)return;const intent=findCategoryPrefix(q);if(intent)return runCategoryIntent(intent.cat,intent.place);try{setStatus(tr().loading,false,0);const rows=await photon(q,1);if(!rows[0])return setStatus(tr().none,true);openPhoton(rows[0]);setStatus('')}catch{setStatus(tr().none,true)}}
function openPhoton(f){const g=f?.geometry?.coordinates;if(!g)return;document.querySelector('#pvExploreDropdown').hidden=true;document.querySelector('#pvExploreInput').value=photonTitle(f);const p=f.properties||{},kind=String(p.osm_value||p.type||'').toLowerCase();let z=13;if(/country/.test(kind))z=5;else if(/state/.test(kind))z=7;else if(/city|town|village/.test(kind))z=12;else if(/street|road/.test(kind))z=16;else if(/house|restaurant|hotel|pharmacy|shop/.test(kind))z=17;map.flyTo({center:g,zoom:z,duration:1100,essential:true})}
async function runCategoryIntent(cat,place){if(!cat)return;if(place){try{setStatus(tr().loading,false,0);const r=(await photon(place,1))[0];if(!r)return setStatus(tr().none,true);map.flyTo({center:r.geometry.coordinates,zoom:13,duration:1000,essential:true});await new Promise(res=>setTimeout(res,1100))}catch{return setStatus(tr().none,true)}}return searchCategory(cat)}

function overpassRadius(){const z=map.getZoom?.()||0;if(z>=16)return700;if(z>=15)return1100;if(z>=14)return1800;if(z>=13)return2600;if(z>=12)return4000;return6500}
async function overpass(query,timeout=14){const endpoints=['https://overpass.kumi.systems/api/interpreter','https://overpass.nchc.org.tw/api/interpreter'];let last;for(const endpoint of endpoints){try{const ctrl=new AbortController();const to=setTimeout(()=>ctrl.abort(),timeout*1000);const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(query),signal:ctrl.signal});clearTimeout(to);if(!r.ok)throw new Error(String(r.status));return (await r.json()).elements||[]}catch(e){last=e}}throw last||new Error('overpass')}
function elementPoint(e){if(Number.isFinite(e.lat)&&Number.isFinite(e.lon))return[e.lon,e.lat];if(e.center&&Number.isFinite(e.center.lat)&&Number.isFinite(e.center.lon))return[e.center.lon,e.center.lat];return null}
function localizedTagName(tags={}){const l=lang();return tags[`name:${l}`]||tags.name||tags['name:en']||tags.brand||''}
function kindFromTags(t={}){const x=t.amenity||t.shop||t.tourism||t.leisure||t.healthcare||t.railway||t.aeroway||'';const mapIt={restaurant:'Ristorante',cafe:'Caffè',bar:'Bar',pub:'Pub',pharmacy:'Farmacia',hospital:'Ospedale',clinic:'Clinica',parking:'Parcheggio',fuel:'Distributore',atm:'Bancomat',supermarket:'Supermercato',hotel:'Hotel',guest_house:'Affittacamere',hostel:'Ostello',museum:'Museo',attraction:'Attrazione',station:'Stazione',aerodrome:'Aeroporto'};return lang()==='it'?(mapIt[x]||String(x||'Luogo').replaceAll('_',' ')):(String(x||'Place').replaceAll('_',' '))}
function osmUrl(e){const type=e.type==='node'?'node':e.type==='way'?'way':'relation';return`https://www.openstreetmap.org/${type}/${e.id}`}
async function searchCategory(cat){if(!map||map.getZoom()<8.5)return setStatus(tr().zoom,true);activeCat=cat.id;renderLanguage();const c=map.getCenter(),radius=overpassRadius();setStatus(`${tr().loading} ${catLabel(cat)}`,false,0);try{const q=`[out:json][timeout:12];(${cat.q}(around:${radius},${c.lat},${c.lng}););out center tags 80;`;const rows=(await overpass(q)).map((e,i)=>{const p=elementPoint(e);return p&&localizedTagName(e.tags)?{...e,_p:p,_rid:`r${Date.now()}_${i}`} : null}).filter(Boolean).slice(0,80);renderCategoryResults(rows,cat);setStatus(`${rows.length} ${tr().results} · ${catLabel(cat)}`,false,3200)}catch(e){console.warn('Nearby search',e);setStatus(tr().none,true)}}
function clearCategoryResults(){activeCat=null;renderLanguage();resultById.clear();if(!map)return;try{if(map.getLayer('pv-nearby-labels'))map.removeLayer('pv-nearby-labels');if(map.getLayer('pv-nearby-points'))map.removeLayer('pv-nearby-points');if(map.getSource('pv-nearby'))map.removeSource('pv-nearby')}catch{}}
function renderCategoryResults(rows,cat){clearCategoryResults();activeCat=cat.id;renderLanguage();resultById=new Map(rows.map(r=>[r._rid,r]));const data={type:'FeatureCollection',features:rows.map(r=>({type:'Feature',geometry:{type:'Point',coordinates:r._p},properties:{rid:r._rid,name:localizedTagName(r.tags)}}))};try{map.addSource('pv-nearby',{type:'geojson',data});map.addLayer({id:'pv-nearby-points',type:'circle',source:'pv-nearby',paint:{'circle-radius':8,'circle-color':'#72e8ff','circle-stroke-width':2,'circle-stroke-color':'#07101b'}});map.addLayer({id:'pv-nearby-labels',type:'symbol',source:'pv-nearby',minzoom:14,layout:{'text-field':['get','name'],'text-size':11,'text-offset':[0,1.35],'text-anchor':'top','text-allow-overlap':false},paint:{'text-color':'#ffffff','text-halo-color':'#07101b','text-halo-width':1.4}});map.on('click','pv-nearby-points',e=>{const rid=e.features?.[0]?.properties?.rid,r=resultById.get(rid);if(r)showPoi(r,r._p)});map.on('mouseenter','pv-nearby-points',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','pv-nearby-points',()=>map.getCanvas().style.cursor='')}catch(e){console.warn('Category markers',e)}}

function distance(a,b){const R=6371000,d2r=Math.PI/180,dLat=(b[1]-a[1])*d2r,dLon=(b[0]-a[0])*d2r,la1=a[1]*d2r,la2=b[1]*d2r;const h=Math.sin(dLat/2)**2+Math.cos(la1)*Math.cos(la2)*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.sqrt(h))}
async function nearestPoi(lngLat,renderedName=''){const z=map.getZoom?.()||14,r=z>=17?45:z>=16?70:z>=15?110:180;const q=`[out:json][timeout:10];(nwr(around:${r},${lngLat.lat},${lngLat.lng})[amenity];nwr(around:${r},${lngLat.lat},${lngLat.lng})[shop];nwr(around:${r},${lngLat.lat},${lngLat.lng})[tourism];nwr(around:${r},${lngLat.lat},${lngLat.lng})[leisure];nwr(around:${r},${lngLat.lat},${lngLat.lng})[healthcare];nwr(around:${r},${lngLat.lat},${lngLat.lng})[office];nwr(around:${r},${lngLat.lat},${lngLat.lng})[craft];);out center tags 40;`;const rows=(await overpass(q,10)).map(e=>({...e,_p:elementPoint(e)})).filter(e=>e._p&&localizedTagName(e.tags));if(!rows.length)return null;const target=norm(renderedName);rows.sort((a,b)=>{const an=norm(localizedTagName(a.tags)),bn=norm(localizedTagName(b.tags));const am=target&&(an===target?0:an.includes(target)||target.includes(an)?15:80),bm=target&&(bn===target?0:bn.includes(target)||target.includes(bn)?15:80);return distance([lngLat.lng,lngLat.lat],a._p)+am-(distance([lngLat.lng,lngLat.lat],b._p)+bm)});return rows[0]}
function visiblePoiLayers(){return(map.getStyle?.().layers||[]).filter(l=>l.type==='symbol'&&(l['source-layer']==='poi'||/poi|amenity|shop|restaurant|pharmacy|hospital|hotel|cafe|museum|attraction/i.test(l.id||''))).map(l=>l.id)}
function bindPoiLayers(){if(!map?.isStyleLoaded?.())return;for(const id of visiblePoiLayers()){if(boundPoiLayers.has(id)||!map.getLayer(id))continue;boundPoiLayers.add(id);try{map.on('click',id,onRenderedPoi);map.on('mouseenter',id,()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave',id,()=>map.getCanvas().style.cursor='')}catch{}}}
async function onRenderedPoi(e){if((map.getZoom?.()||0)<12)return;const f=e.features?.[0];if(!f)return;const p=f.properties||{},name=p[`name:${lang()}`]||p.name||p['name:en']||'';const ll=e.lngLat;showPoiLoading(name||kindFromTags(p));try{const found=await nearestPoi(ll,name);if(found)return showPoi(found,found._p);showTilePoi(p,ll)}catch{showTilePoi(p,ll)}}
function openInfo(){document.querySelectorAll('.sheet.open').forEach(s=>{s.classList.remove('open');s.setAttribute('aria-hidden','true')});const s=document.querySelector('#infoSheet');if(!s)return;s.classList.add('open');s.setAttribute('aria-hidden','false');document.querySelector('#scrim')?.classList.add('open')}
function showPoiLoading(title){document.querySelector('#infoKicker').textContent=tr().details;document.querySelector('#infoTitle').textContent=title||'…';document.querySelector('#infoBody').innerHTML=`<div class="pv-poi-loading"><span class="pv-poi-spinner"></span>${esc(tr().loading)}</div>`;openInfo()}
function addressFrom(t={}){const street=[t['addr:street'],t['addr:housenumber']].filter(Boolean).join(' ');return[street,t['addr:postcode'],t['addr:city']||t['addr:town']||t['addr:village']].filter(Boolean).join(', ')}
function safeWebsite(v){if(!v)return'';try{const u=new URL(/^https?:\/\//i.test(v)?v:`https://${v}`);return['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}}
function wikiUrl(v){if(!v)return'';const i=v.indexOf(':');if(i<1)return'';const l=v.slice(0,i),title=v.slice(i+1);return`https://${encodeURIComponent(l)}.wikipedia.org/wiki/${encodeURIComponent(title.replaceAll(' ','_'))}`}
function detailRow(label,value){return value?`<div class="source-card"><b>${esc(label)}</b><span>${esc(value)}</span></div>`:''}
function showPoi(e,point){const t=e.tags||{},name=localizedTagName(t)||kindFromTags(t),kind=kindFromTags(t),web=safeWebsite(t.website||t['contact:website']||t.url),phone=t.phone||t['contact:phone']||'',addr=addressFrom(t),wiki=wikiUrl(t.wikipedia),wd=t.wikidata?`https://www.wikidata.org/wiki/${encodeURIComponent(t.wikidata)}`:'';document.querySelector('#infoKicker').textContent=tr().details;document.querySelector('#infoTitle').textContent=name;const actions=[web?`<a class="link-btn primary-link" href="${esc(web)}" target="_blank" rel="noopener">${esc(tr().website)} ↗</a>`:'',`<a class="link-btn" href="${esc(osmUrl(e))}" target="_blank" rel="noopener">OpenStreetMap ↗</a>`,wiki?`<a class="link-btn" href="${esc(wiki)}" target="_blank" rel="noopener">Wikipedia ↗</a>`:'',wd?`<a class="link-btn" href="${esc(wd)}" target="_blank" rel="noopener">Wikidata ↗</a>`:''].filter(Boolean).join('');document.querySelector('#infoBody').innerHTML=`<div class="info-grid"><div class="info-metric"><small>Tipo</small><b>${esc(kind)}</b></div><div class="info-metric"><small>Coordinate</small><b>${Number(point?.[1]).toFixed(5)}, ${Number(point?.[0]).toFixed(5)}</b></div></div>${detailRow(tr().address,addr)}${detailRow(tr().hours,t.opening_hours)}${detailRow(tr().phone,phone)}${detailRow(tr().cuisine,t.cuisine?.replaceAll(';',', '))}${detailRow(tr().brand,t.brand)}<div class="source-card"><b class="ok">${esc(tr().source)}</b><span>OpenStreetMap · dati dell'elemento selezionato</span></div><div class="info-actions">${actions}</div>`;openInfo()}
function showTilePoi(p,ll){const name=p[`name:${lang()}`]||p.name||p['name:en']||kindFromTags(p);document.querySelector('#infoKicker').textContent=tr().details;document.querySelector('#infoTitle').textContent=name;document.querySelector('#infoBody').innerHTML=`<div class="info-grid"><div class="info-metric"><small>Tipo</small><b>${esc(kindFromTags(p))}</b></div><div class="info-metric"><small>Coordinate</small><b>${ll.lat.toFixed(5)}, ${ll.lng.toFixed(5)}</b></div></div><div class="source-card"><b class="ok">${esc(tr().source)}</b><span>OpenStreetMap / OpenFreeMap</span></div>`;openInfo()}

async function waitMap(){for(let i=0;i<160;i++){if(window.__PV_MAP__?.getZoom){map=window.__PV_MAP__;break}await new Promise(r=>setTimeout(r,100))}if(!map)return;updateStrip();map.on('zoomend',updateStrip);map.on('moveend',updateStrip);map.on('styledata',()=>setTimeout(bindPoiLayers,120));setTimeout(bindPoiLayers,400)}
addCss();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{createUi();waitMap()},{once:true});else{createUi();waitMap()}
