const lang=()=>{try{return localStorage.getItem('pv_language')||'it'}catch{return'it'}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const normalize=s=>String(s||'').trim().toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');

const words={
  it:{title:'Cerca per categoria',area:'nell’area visibile',zoom:'Avvicinati prima a una città o a una zona abitata.',loading:'Cerco nei dati OpenStreetMap…',none:'Nessun risultato trovato.',results:'Risultati',type:'Scrivi almeno 2 caratteri.',category:'Categoria',distance:'distanza'},
  en:{title:'Search by category',area:'in the visible area',zoom:'Zoom into a city or populated area first.',loading:'Searching OpenStreetMap data…',none:'No results found.',results:'Results',type:'Type at least 2 characters.',category:'Category',distance:'distance'},
  fr:{title:'Rechercher par catégorie',area:'dans la zone visible',zoom:'Zoomez d’abord sur une ville ou une zone habitée.',loading:'Recherche dans OpenStreetMap…',none:'Aucun résultat.',results:'Résultats',type:'Saisissez au moins 2 caractères.',category:'Catégorie',distance:'distance'},
  es:{title:'Buscar por categoría',area:'en el área visible',zoom:'Acércate primero a una ciudad o zona habitada.',loading:'Buscando en OpenStreetMap…',none:'No se encontraron resultados.',results:'Resultados',type:'Escribe al menos 2 caracteres.',category:'Categoría',distance:'distancia'},
  de:{title:'Nach Kategorie suchen',area:'im sichtbaren Bereich',zoom:'Zoome zuerst in eine Stadt oder ein bewohntes Gebiet.',loading:'OpenStreetMap wird durchsucht…',none:'Keine Ergebnisse.',results:'Ergebnisse',type:'Mindestens 2 Zeichen eingeben.',category:'Kategorie',distance:'Entfernung'},
  ru:{title:'Поиск по категории',area:'в видимой области',zoom:'Сначала приблизьте город или населённую местность.',loading:'Поиск в OpenStreetMap…',none:'Ничего не найдено.',results:'Результаты',type:'Введите минимум 2 символа.',category:'Категория',distance:'расстояние'},
  hi:{title:'श्रेणी के अनुसार खोजें',area:'दिखाई दे रहे क्षेत्र में',zoom:'पहले किसी शहर या आबादी वाले क्षेत्र पर ज़ूम करें।',loading:'OpenStreetMap में खोजा जा रहा है…',none:'कोई परिणाम नहीं मिला।',results:'परिणाम',type:'कम से कम 2 अक्षर लिखें।',category:'श्रेणी',distance:'दूरी'},
  pt:{title:'Pesquisar por categoria',area:'na área visível',zoom:'Aproxime primeiro uma cidade ou zona habitada.',loading:'A pesquisar no OpenStreetMap…',none:'Nenhum resultado.',results:'Resultados',type:'Escreva pelo menos 2 caracteres.',category:'Categoria',distance:'distância'},
  zh:{title:'按类别搜索',area:'在当前可见区域',zoom:'请先放大到城市或有人居住的区域。',loading:'正在搜索 OpenStreetMap…',none:'未找到结果。',results:'结果',type:'至少输入 2 个字符。',category:'类别',distance:'距离'},
  ja:{title:'カテゴリから検索',area:'表示中のエリア',zoom:'まず都市または居住地域まで拡大してください。',loading:'OpenStreetMap を検索中…',none:'結果が見つかりません。',results:'結果',type:'2文字以上入力してください。',category:'カテゴリ',distance:'距離'}
};
const tr=()=>words[lang()]||words.en;

const cats=[
  {id:'restaurant',icon:'🍴',labels:{it:'Ristoranti',en:'Restaurants',fr:'Restaurants',es:'Restaurantes',de:'Restaurants',ru:'Рестораны',hi:'रेस्तराँ',pt:'Restaurantes',zh:'餐厅',ja:'レストラン'},selectors:['nwr["amenity"="restaurant"]'],keys:['restaurant','restaurants','ristorante','ristoranti','restaurante','restaurantes','ресторан','рестораны','रेस्तराँ','餐厅','レストラン']},
  {id:'hotel',icon:'▣',labels:{it:'Hotel',en:'Hotels',fr:'Hôtels',es:'Hoteles',de:'Hotels',ru:'Отели',hi:'होटल',pt:'Hotéis',zh:'酒店',ja:'ホテル'},selectors:['nwr["tourism"~"hotel|guest_house|hostel|motel"]'],keys:['hotel','hotels','hôtel','hôtels','hoteles','отель','отели','होटल','酒店','ホテル']},
  {id:'parking',icon:'P',labels:{it:'Parcheggi',en:'Parking',fr:'Parkings',es:'Aparcamientos',de:'Parkplätze',ru:'Парковки',hi:'पार्किंग',pt:'Estacionamentos',zh:'停车场',ja:'駐車場'},selectors:['nwr["amenity"="parking"]'],keys:['parking','parcheggio','parcheggi','parkplatz','parkplätze','aparcamiento','aparcamientos','парковка','парковки','पार्किंग','停车场','駐車場']},
  {id:'cafe',icon:'☕',labels:{it:'Bar e caffè',en:'Cafés & bars',fr:'Cafés et bars',es:'Cafés y bares',de:'Cafés & Bars',ru:'Кафе и бары',hi:'कैफ़े और बार',pt:'Cafés e bares',zh:'咖啡馆和酒吧',ja:'カフェ・バー'},selectors:['nwr["amenity"~"cafe|bar|pub"]'],keys:['cafe','caffè','bar','bars','pub','pubs','café','кафе','бар','कैफ़े','咖啡馆','酒吧','カフェ','バー']},
  {id:'supermarket',icon:'□',labels:{it:'Supermercati',en:'Supermarkets',fr:'Supermarchés',es:'Supermercados',de:'Supermärkte',ru:'Супермаркеты',hi:'सुपरमार्केट',pt:'Supermercados',zh:'超市',ja:'スーパー'},selectors:['nwr["shop"="supermarket"]'],keys:['supermarket','supermarkets','supermercato','supermercati','supermarché','supermercado','supermarkt','супермаркет','सुपरमार्केट','超市','スーパー']},
  {id:'pharmacy',icon:'✚',labels:{it:'Farmacie',en:'Pharmacies',fr:'Pharmacies',es:'Farmacias',de:'Apotheken',ru:'Аптеки',hi:'फ़ार्मेसी',pt:'Farmácias',zh:'药店',ja:'薬局'},selectors:['nwr["amenity"="pharmacy"]'],keys:['pharmacy','pharmacies','farmacia','farmacie','pharmacie','apotheke','apotheken','аптека','аптеки','फ़ार्मेसी','药店','薬局']},
  {id:'hospital',icon:'H',labels:{it:'Ospedali',en:'Hospitals',fr:'Hôpitaux',es:'Hospitales',de:'Krankenhäuser',ru:'Больницы',hi:'अस्पताल',pt:'Hospitais',zh:'医院',ja:'病院'},selectors:['nwr["amenity"~"hospital|clinic"]'],keys:['hospital','hospitals','ospedale','ospedali','clinica','cliniche','hôpital','hospitales','krankenhaus','больница','अस्पताल','医院','病院']},
  {id:'fuel',icon:'⛽',labels:{it:'Carburante',en:'Fuel',fr:'Stations-service',es:'Gasolineras',de:'Tankstellen',ru:'Заправки',hi:'ईंधन',pt:'Postos',zh:'加油站',ja:'ガソリンスタンド'},selectors:['nwr["amenity"="fuel"]'],keys:['fuel','gas station','benzina','distributore','carburante','station-service','gasolinera','tankstelle','заправка','ईंधन','加油站','ガソリンスタンド']},
  {id:'charging',icon:'⚡',labels:{it:'Ricarica EV',en:'EV charging',fr:'Recharge VE',es:'Carga EV',de:'E-Ladestationen',ru:'Зарядки ЭМ',hi:'ईवी चार्जिंग',pt:'Carregamento EV',zh:'电动车充电',ja:'EV充電'},selectors:['nwr["amenity"="charging_station"]'],keys:['charging station','ev charging','ricarica','colonnina','ladestation','зарядка','ईवी चार्जिंग','充电站','ev充電']},
  {id:'museum',icon:'◇',labels:{it:'Musei',en:'Museums',fr:'Musées',es:'Museos',de:'Museen',ru:'Музеи',hi:'संग्रहालय',pt:'Museus',zh:'博物馆',ja:'博物館'},selectors:['nwr["tourism"="museum"]'],keys:['museum','museums','museo','musei','musée','musées','museos','museen','музей','музеи','संग्रहालय','博物馆','博物館']},
  {id:'attraction',icon:'◎',labels:{it:'Attrazioni',en:'Attractions',fr:'Attractions',es:'Atracciones',de:'Sehenswürdigkeiten',ru:'Достопримечательности',hi:'आकर्षण',pt:'Atrações',zh:'景点',ja:'観光スポット'},selectors:['nwr["tourism"~"attraction|viewpoint|zoo|theme_park"]'],keys:['attraction','attractions','attrazione','attrazioni','sehenswürdigkeit','достопримечательность','आकर्षण','景点','観光スポット']},
  {id:'station',icon:'⇆',labels:{it:'Stazioni',en:'Stations',fr:'Gares',es:'Estaciones',de:'Bahnhöfe',ru:'Станции',hi:'स्टेशन',pt:'Estações',zh:'车站',ja:'駅'},selectors:['nwr["railway"="station"]','nwr["public_transport"="station"]'],keys:['station','stations','stazione','stazioni','gare','gares','estacion','estaciones','bahnhof','станция','स्टेशन','车站','駅']},
  {id:'airport',icon:'✈',labels:{it:'Aeroporti',en:'Airports',fr:'Aéroports',es:'Aeropuertos',de:'Flughäfen',ru:'Аэропорты',hi:'हवाई अड्डे',pt:'Aeroportos',zh:'机场',ja:'空港'},selectors:['nwr["aeroway"="aerodrome"]'],keys:['airport','airports','aeroporto','aeroporti','aéroport','aeropuerto','flughafen','аэропорт','हवाई अड्डा','机场','空港']},
  {id:'atm',icon:'€',labels:{it:'Bancomat',en:'ATMs',fr:'Distributeurs',es:'Cajeros',de:'Geldautomaten',ru:'Банкоматы',hi:'एटीएम',pt:'Caixas eletrônicos',zh:'ATM',ja:'ATM'},selectors:['nwr["amenity"="atm"]'],keys:['atm','bancomat','cajero','geldautomat','банкомат','एटीएम']},
  {id:'city',icon:'◆',labels:{it:'Città e paesi',en:'Cities & towns',fr:'Villes',es:'Ciudades',de:'Städte',ru:'Города',hi:'शहर',pt:'Cidades',zh:'城市',ja:'都市'},selectors:['nwr["place"~"city|town|village"]'],keys:['città','citta','cittadine','paesi','city','cities','town','towns','ville','villes','ciudad','ciudades','stadt','städte','город','города','शहर','城市','都市']},
  {id:'street',icon:'═',labels:{it:'Vie e strade',en:'Streets & roads',fr:'Rues et routes',es:'Calles y carreteras',de:'Straßen',ru:'Улицы и дороги',hi:'सड़कें',pt:'Ruas e estradas',zh:'街道和道路',ja:'道路'},selectors:['way["highway"]["name"]'],keys:['via','vie','strada','strade','street','streets','road','roads','rue','rues','calle','calles','straße','strassen','улица','дорога','सड़क','街道','道路']}
];
const catLabel=c=>c.labels[lang()]||c.labels.en;

let input,status,results,categories,aborter=null,timer=null,seq=0;
const photonCache=new Map();
async function photon(q,limit=10,layers=[]){
  const map=window.__PV_MAP__,center=map?.getCenter?.(),zoom=map?.getZoom?.(),key=JSON.stringify([q,limit,lang(),layers,center&&[center.lng.toFixed(2),center.lat.toFixed(2)]]);if(photonCache.has(key))return photonCache.get(key);
  aborter?.abort();aborter=new AbortController();
  const u=new URL('https://photon.komoot.io/api/');u.searchParams.set('q',q);u.searchParams.set('limit',String(limit));u.searchParams.set('lang',lang());
  if(center){u.searchParams.set('lat',String(center.lat));u.searchParams.set('lon',String(center.lng));if(Number.isFinite(zoom))u.searchParams.set('zoom',String(Math.max(1,Math.min(18,zoom))))}
  layers.forEach(x=>u.searchParams.append('layer',x));
  try{let r=await fetch(u,{signal:aborter.signal});if(!r.ok&&u.searchParams.has('lang')){u.searchParams.delete('lang');r=await fetch(u,{signal:aborter.signal})}if(!r.ok)throw new Error(`Photon ${r.status}`);const j=await r.json(),out=j.features||[];photonCache.set(key,out);if(photonCache.size>50)photonCache.delete(photonCache.keys().next().value);return out}catch(e){if(e?.name!=='AbortError')console.warn('Perkussus search',e);return[]}
}

const overpassServers=['https://overpass.private.coffee/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://maps.mail.ru/osm/tools/overpass/api/interpreter'];
async function overpass(q){let last;for(const endpoint of overpassServers){const c=new AbortController(),t=setTimeout(()=>c.abort(),14000);try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(q),signal:c.signal});clearTimeout(t);if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}catch(e){clearTimeout(t);last=e;console.warn('Overpass',endpoint,e)}}throw last||new Error('Overpass unavailable')}
const haversine=(a,b,c,d)=>{const R=6371e3,r=x=>x*Math.PI/180,p1=r(a),p2=r(c),dp=r(c-a),dl=r(d-b),x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
function radius(z,c){if(c.id==='city')return z>=10?40000:90000;if(c.id==='street')return z>=15?2500:6500;if(z>=15)return2500;if(z>=13)return5000;if(z>=11)return10000;return20000}
function overpassSelector(s,r,lat,lon){const m=String(s).match(/^(nwr|node|way|relation)(.*)$/);return m?`${m[1]}(around:${Math.round(r)},${lat},${lon})${m[2]};`:''}

function resultName(f){const p=f.properties||{};return p.name||[p.street,p.housenumber].filter(Boolean).join(' ')||p.city||p.locality||p.country||'Luogo'}
function subtitle(f){const p=f.properties||{};return[p.street,p.district,p.city||p.locality,p.state,p.country].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join(' · ')}
function resultZoom(f){const p=f.properties||{},v=String(p.osm_value||p.type||'').toLowerCase(),layer=String(p.type||'').toLowerCase();if(v==='country'||layer==='country')return 5;if(['state','region'].includes(v)||layer==='state')return 7;if(['city','town','village','locality'].includes(v)||['city','locality'].includes(layer))return 12;if(v==='street'||layer==='street'||p.osm_key==='highway')return 16;return 17}
function closeSearch(){document.querySelector('#searchSheet [data-close]')?.click()}
function fireMapClick(map,lon,lat){try{const ll={lng:lon,lat};const p=map.project([lon,lat]);map.fire('click',{lngLat:ll,point:p,originalEvent:null})}catch(e){console.warn('Perkussus result click',e)}}
function goPhoton(f){const c=f.geometry?.coordinates,map=window.__PV_MAP__;if(!map||!Array.isArray(c))return;const lon=Number(c[0]),lat=Number(c[1]);closeSearch();map.flyTo({center:[lon,lat],zoom:resultZoom(f),duration:1200,essential:true});map.once('moveend',()=>setTimeout(()=>fireMapClick(map,lon,lat),250))}

function renderPhoton(rows){results.innerHTML='';if(!rows.length){results.innerHTML=`<div class="pv-empty">${esc(tr().none)}</div>`;return}results.innerHTML=`<div class="pv-results-head">${esc(tr().results)}</div>`;rows.slice(0,20).forEach(f=>{const b=document.createElement('button');b.type='button';b.className='pv-result';b.innerHTML=`<span class="pv-result-icon">⌖</span><span class="pv-result-copy"><b>${esc(resultName(f))}</b><small>${esc(subtitle(f)||[f.properties?.osm_value,f.properties?.osm_key].filter(Boolean).join(' · '))}</small></span>`;b.addEventListener('click',()=>goPhoton(f));results.append(b)})}

function goOsm(r){const map=window.__PV_MAP__;if(!map)return;closeSearch();map.flyTo({center:[r.lon,r.lat],zoom:r.cat.id==='city'?12:r.cat.id==='street'?16:17,duration:1200,essential:true});map.once('moveend',()=>setTimeout(()=>fireMapClick(map,r.lon,r.lat),250))}
function renderOsm(rows){results.innerHTML='';if(!rows.length){results.innerHTML=`<div class="pv-empty">${esc(tr().none)}</div>`;return}results.innerHTML=`<div class="pv-results-head">${esc(tr().results)}</div>`;rows.slice(0,30).forEach(r=>{const b=document.createElement('button');b.type='button';b.className='pv-result';const name=r.name||catLabel(r.cat),sub=[catLabel(r.cat),r.tags['addr:street'],r.tags['addr:city'],`${Math.round(r.distance)} m`].filter(Boolean).join(' · ');b.innerHTML=`<span class="pv-result-icon">${esc(r.cat.icon)}</span><span class="pv-result-copy"><b>${esc(name)}</b><small>${esc(sub)}</small></span>`;b.addEventListener('click',()=>goOsm(r));results.append(b)})}

async function searchCategory(cat,centerOverride=null){const map=window.__PV_MAP__;if(!map)return;const z=map.getZoom(),center=centerOverride||map.getCenter();if(!centerOverride&&z<8){status.textContent=tr().zoom;return}status.textContent=`${tr().loading} ${catLabel(cat)} ${tr().area}`;const r=centerOverride?9000:radius(z,cat),selectors=cat.selectors.map(s=>overpassSelector(s,r,center.lat,center.lng)).join(''),q=`[out:json][timeout:14];(${selectors});out center tags 60;`;try{const j=await overpass(q),seen=new Set(),rows=[];for(const e of j.elements||[]){const lat=Number(e.lat??e.center?.lat),lon=Number(e.lon??e.center?.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon))continue;const tags=e.tags||{},name=tags[`name:${lang()}`]||tags.name||'';const key=cat.id==='street'&&name?`street:${normalize(name)}`:`${e.type}:${e.id}`;if(seen.has(key))continue;seen.add(key);rows.push({type:e.type,id:e.id,lat,lon,tags,name,cat,distance:haversine(center.lat,center.lng,lat,lon)})}rows.sort((a,b)=>a.distance-b.distance);status.textContent=rows.length?`${rows.length} · ${catLabel(cat)} ${tr().area}`:tr().none;renderOsm(rows)}catch(e){console.warn('Category search',e);status.textContent=tr().none;renderOsm([])}}

function parseCategory(q){const n=normalize(q);for(const c of cats){const list=[catLabel(c),...c.keys].map(normalize).sort((a,b)=>b.length-a.length);for(const k of list){if(n===k)return{cat:c,where:''};if(n.startsWith(k+' '))return{cat:c,where:q.trim().slice(k.length).trim()};if(n.endsWith(' '+k))return{cat:c,where:q.trim().slice(0,q.trim().length-k.length).trim()}}}return null}
async function submitSearch(q){const parsed=parseCategory(q);if(parsed){if(parsed.where){status.textContent=tr().loading;const places=await photon(parsed.where,5,['city','locality','district','county','state','country']);if(!places.length){status.textContent=tr().none;return}const c=places[0].geometry.coordinates;return searchCategory(parsed.cat,{lng:Number(c[0]),lat:Number(c[1])})}return searchCategory(parsed.cat)}status.textContent=tr().loading;const rows=await photon(q,14);status.textContent=rows.length?`${rows.length} ${tr().results.toLocaleLowerCase()}`:tr().none;renderPhoton(rows)}

function autocomplete(){clearTimeout(timer);const q=input.value.trim(),my=++seq;if(q.length<2){results.innerHTML='';status.textContent=q?tr().type:'';return}timer=setTimeout(async()=>{const rows=await photon(q,9);if(my!==seq)return;status.textContent='';renderPhoton(rows)},360)}

function rebuildCategoryLabels(){const head=document.querySelector('.pv-category-head');if(head)head.innerHTML=`<b>${esc(tr().title)}</b><small>${esc(tr().area)}</small>`;categories?.querySelectorAll('[data-cat]').forEach(b=>{const c=cats.find(x=>x.id===b.dataset.cat);if(c)b.innerHTML=`<span>${esc(c.icon)}</span>${esc(catLabel(c))}`})}

function init(){
  document.querySelectorAll('.pv-category-wrap,.pv-search-results').forEach(x=>x.remove());
  const oldForm=document.querySelector('#searchForm');if(!oldForm)return;const newForm=oldForm.cloneNode(true);oldForm.replaceWith(newForm);
  input=newForm.querySelector('#searchInput');status=document.querySelector('#searchStatus');const body=document.querySelector('#searchSheet .sheet-body');
  const wrap=document.createElement('div');wrap.className='pv-category-wrap';wrap.innerHTML=`<div class="pv-category-head"><b>${esc(tr().title)}</b><small>${esc(tr().area)}</small></div><div class="pv-categories"></div>`;categories=wrap.querySelector('.pv-categories');
  cats.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='pv-cat';b.dataset.cat=c.id;b.innerHTML=`<span>${esc(c.icon)}</span>${esc(catLabel(c))}`;b.addEventListener('click',()=>searchCategory(c));categories.append(b)});
  results=document.createElement('div');results.className='pv-search-results';status.after(wrap);wrap.after(results);
  input.addEventListener('input',autocomplete);input.addEventListener('keydown',e=>{if(e.key==='Escape'){results.innerHTML='';status.textContent=''}});
  document.addEventListener('submit',e=>{if(e.target?.id!=='searchForm')return;e.preventDefault();e.stopImmediatePropagation();const q=document.querySelector('#searchInput')?.value.trim();if(q)submitSearch(q)},{capture:true});
  document.addEventListener('click',e=>{const option=e.target.closest?.('[data-language]');if(option)setTimeout(rebuildCategoryLabels,30)},{capture:true});
}

init();
